/**
 * Do not edit directly, this file was auto-generated.
 */

export default {
  background: "247 34% 6%",
  foreground: "258 26% 97%",
  text: "var(--foreground)",
  card: "249 30% 9%",
  cardForeground: "var(--foreground)",
  panel: "var(--card)",
  border: "253 28% 24%",
  line: "var(--border)",
  input: "249 28% 12%",
  ring: "262 88% 66%",
  themeRing: "hsl(var(--ring))",
  primary: "262 88% 60%",
  primaryForeground: "0 0% 100%",
  primarySoft: "262 88% 20%",
  accent: "294 90% 42%",
  accent2: "190 88% 32%",
  accent3: "200 88% 34%",
  accentForeground: "0 0% 100%",
  accentSoft: "294 90% 16%",
  highlight: "0 0% 100%",
  glow: "296 96% 56%",
  ringMuted: "248 22% 24%",
  danger: "0 84% 60%",
  warning: "43 96% 56%",
  warningSoft: "var(--warning) / 0.1",
  warningSoftStrong: "var(--warning) / 0.2",
  muted: "248 24% 15%",
  mutedForeground: "248 18% 74%",
  surface: "248 26% 11%",
  surface2: "248 26% 16%",
  surfaceVhs: "210 24% 7%",
  surfaceStreak: "240 18% 13%",
  shadowColor: "263 78% 56%",
  lavDeep: "318 82% 60%",
  teamBlue: "200 100% 60%",
  teamRed: "0 85% 60%",
  noirBackground: "352 68% 4%",
  noirForeground: "0 0% 94%",
  noirBorder: "352 44% 24%",
  hardstuckBackground: "120 58% 3%",
  hardstuckForeground: "120 60% 72%",
  hardstuckBorder: "120 42% 22%",
  success: "160 72% 48%",
  successSoft: "var(--success) / 0.2",
  successGlow: "160 72% 38% / 0.6",
  toneTop: "38 92% 60%",
  toneJg: "152 52% 44%",
  toneMid: "265 72% 62%",
  toneBot: "195 75% 56%",
  toneSup: "320 72% 60%",
  auroraG: "var(--accent-2)",
  auroraGLight: "150 100% 85%",
  auroraP: "var(--accent)",
  auroraPLight: "272 80% 85%",
  iconFg: "250 96% 78%",
  accentOverlay: "hsl(var(--accent))",
  ringContrast: "hsl(var(--ring))",
  glowActive: "hsl(var(--glow))",
  textOnAccent: "hsl(var(--foreground))",
  neon: "var(--glow)",
  neonSoft: "hsl(var(--neon))",
  btnBg: "transparent",
  btnFg: "hsl(var(--foreground))",
  hover: "hsl(var(--foreground) / 0.08)",
  focus: "hsl(var(--ring))",
  active: "hsl(var(--foreground) / 0.12)",
  disabled: "0.5",
  loading: "0.6",
  cardHairline: "hsl(var(--border))",
  hairlineW: "1px",
  easeOut: "cubic-bezier(0.16, 1, 0.3, 1)",
  easeSnap: "cubic-bezier(0.2, 0.8, 0.2, 1)",
  durQuick: "140ms",
  durChill: "220ms",
  durSlow: "420ms",
  controlHXs: "24px",
  controlHSm: "32px",
  controlHMd: "40px",
  controlHLg: "48px",
  controlHXl: "56px",
  controlH: "var(--control-h-md)",
  controlRadius: "var(--radius-xl)",
  controlFs: "var(--font-ui)",
  controlPx: "var(--spacing-3)",
  shellWidth: "1280px",
  shellMax: "var(--shell-width)",
  headerStack: "calc(var(--spacing-8) + var(--spacing-4))",
  edgeIris:
    "conic-gradient(\n    from 180deg,\n    hsl(262 88% 60% / 0),\n    hsl(262 88% 60% / 0.72),\n    hsl(var(--accent-3) / 0.72),\n    hsl(318 82% 60% / 0.7),\n    hsl(262 88% 60% / 0)\n  )",
  segActiveGrad:
    "linear-gradient(\n    90deg,\n    hsl(var(--primary-soft) / 0.85),\n    hsl(var(--accent-soft) / 0.85),\n    hsl(var(--accent-2) / 0.8)\n  )",
  reviewResultWinGradient:
    "linear-gradient(\n    90deg,\n    hsl(var(--success) / 0.22),\n    hsl(var(--accent) / 0.18)\n  )",
  reviewResultLossGradient:
    "linear-gradient(\n    90deg,\n    hsl(var(--danger) / 0.24),\n    hsl(var(--primary) / 0.2)\n  )",
  segActiveBase: "hsl(var(--card))",
  shadow: "0 10px 30px hsl(250 38% 2% / 0.32)",
  shadowDropdown: "0 12px 40px hsl(var(--shadow-color) / 0.55)",
  shadowNeoSm:
    "calc(var(--spacing-1)) calc(var(--spacing-1)) calc(var(--spacing-2))\n      hsl(var(--panel) / 0.72),\n    calc(var(--spacing-1) * -1) calc(var(--spacing-1) * -1) calc(var(--spacing-2))\n      hsl(var(--foreground) / 0.06)",
  shadowNeo:
    "calc(var(--spacing-3)) calc(var(--spacing-3)) var(--spacing-5)\n      hsl(var(--panel) / 0.72),\n    calc(var(--spacing-3) * -1) calc(var(--spacing-3) * -1) var(--spacing-5)\n      hsl(var(--foreground) / 0.06)",
  shadowNeoStrong:
    "var(--spacing-4) var(--spacing-4) var(--spacing-6) hsl(var(--panel) / 0.72),\n    calc(var(--spacing-4) * -1) calc(var(--spacing-4) * -1) var(--spacing-6)\n      hsl(var(--foreground) / 0.08)",
  shadowNeoInset:
    "inset var(--spacing-1) var(--spacing-1) var(--spacing-3)\n      hsl(var(--panel) / 0.85),\n    inset calc(var(--spacing-1) * -1) calc(var(--spacing-1) * -1) var(--spacing-3)\n      hsl(var(--foreground) / 0.08)",
  shadowRing: "0 0 var(--spacing-3) hsl(var(--ring))",
  shadowNeoSoft:
    "0 var(--spacing-1) var(--spacing-3) calc(var(--spacing-1) * -1)\n      hsl(var(--shadow-color))",
  shadowGlowSm: "0 0 var(--spacing-2) var(--glow-active)",
  shadowGlowMd: "0 0 var(--spacing-4) var(--glow-active)",
  shadowGlowLg: "0 0 var(--spacing-5) var(--glow-active)",
  shadowGlowXl: "0 var(--spacing-2) var(--spacing-6) var(--glow-active)",
  shadowNavActive:
    "0 0 0 var(--hairline-w) hsl(var(--ring) / 0.35),\n    0 var(--spacing-2) var(--spacing-6) hsl(var(--ring) / 0.2)",
  shadowOutlineSubtle: "0 0 0 var(--hairline-w) hsl(var(--border) / 0.12)",
  shadowOutlineFaint: "0 0 0 var(--hairline-w) hsl(var(--border) / 0.08)",
  shadowBadge:
    "inset 0 var(--hairline-w) 0 hsl(var(--foreground) / 0.06),\n    0 0 0 var(--hairline-w) hsl(var(--card-hairline) / 0.35),\n    0 var(--spacing-3) var(--spacing-4) hsl(var(--shadow-color) / 0.18)",
  shadowInsetContrast: "inset 0 0 0 var(--hairline-w) var(--ring-contrast)",
  shadowInsetHairline:
    "inset 0 0 0 var(--hairline-w) hsl(var(--card-hairline))",
  shadowGlowCurrent: "0 0 var(--spacing-2) currentColor",
  shadowNeonSoft:
    "0 0 var(--spacing-2) var(--neon),\n    0 0 var(--spacing-4) var(--neon-soft)",
  shadowNeonStrong:
    "0 0 var(--spacing-3) var(--neon),\n    0 0 var(--spacing-5) var(--neon-soft)",
  shadowControl:
    "inset 0 var(--spacing-1) var(--spacing-2) 0 rgb(0 0 0 / 0.06),\n    0 0 0 var(--hairline-w) hsl(var(--border) / 0.12)",
  shadowControlHover:
    "0 var(--spacing-1) var(--spacing-2) hsl(var(--shadow-color) / 0.3)",
  lgViolet: "var(--ring)",
  lgCyan: "var(--accent-2)",
  lgPink: "var(--lav-deep)",
  lgBlack: "var(--background)",
  glowStrong: "var(--ring) / 0.55",
  glowSoft: "var(--accent) / 0.25",
  space1: "var(--spacing-1)",
  space2: "var(--spacing-2)",
  space3: "var(--spacing-3)",
  space4: "var(--spacing-4)",
  space5: "var(--spacing-5)",
  space6: "var(--spacing-6)",
  space7: "var(--spacing-7)",
  space8: "var(--spacing-8)",
  fontSizeMd: "var(--font-body)",
  fontWeightBold: "800",
  shadowNeon:
    "0 0 var(--space-1) hsl(var(--neon) / 0.55),\n    0 0 calc(var(--space-3) - var(--space-1) / 2) hsl(var(--neon) / 0.35),\n    0 0 calc(var(--space-4) + var(--space-1) / 2) hsl(var(--neon) / 0.2)",
  fontLabel: "12px",
  fontUi: "15px",
  fontBody: "19px",
  fontTitle: "24px",
  fontTitleLg: "30px",
  btnPrimaryHoverShadow:
    "0 calc(var(--space-1) / 2) calc(var(--space-3) / 2)\n    calc(-1 * var(--space-1) / 4) hsl(var(--accent) / 0.25)",
  btnPrimaryActiveShadow:
    "inset 0 0 0 calc(var(--space-1) / 4)\n    hsl(var(--accent) / 0.6)",
  pillarWaveStart: "var(--accent)",
  pillarWaveEnd: "var(--accent-2)",
  pillarWaveShadow: "var(--accent) / 0.35",
  pillarTradingStart: "var(--lav-deep)",
  pillarTradingEnd: "var(--accent)",
  pillarTradingShadow: "var(--lav-deep) / 0.35",
  pillarVisionStart: "var(--success)",
  pillarVisionEnd: "var(--accent-2)",
  pillarVisionShadow: "var(--success) / 0.35",
  pillarTempoStart: "var(--ring)",
  pillarTempoEnd: "var(--accent)",
  pillarTempoShadow: "var(--ring) / 0.35",
  pillarPositioningStart: "var(--accent-2)",
  pillarPositioningEnd: "var(--primary)",
  pillarPositioningShadow: "var(--accent-2) / 0.35",
  pillarCommsStart: "var(--lav-deep)",
  pillarCommsEnd: "var(--primary)",
  pillarCommsShadow: "var(--primary) / 0.35",
  cardOverlayScanlines:
    "repeating-linear-gradient(\n    to bottom,\n    hsl(var(--foreground) / 0.035) 0,\n    hsl(var(--foreground) / 0.035) var(--spacing-0-25),\n    transparent var(--spacing-0-5),\n    transparent calc(var(--spacing-0-5) + var(--spacing-0-25))\n  )",
  heroDividerBlur: "calc(var(--spacing-1) * 1.5)",
  visuallyHiddenTop: "-9999px",
  warningForeground: "0 0% 6%",
  successForeground: "0 0% 6%",
  auroraGLightColor: "hsl(var(--aurora-g-light))",
  auroraPLightColor: "hsl(var(--aurora-p-light))",
  spacing0125: "calc(var(--spacing-1) / 8)",
  spacing025: "calc(var(--spacing-1) / 4)",
  spacing05: "calc(var(--spacing-1) / 2)",
  spacing075: "calc(var(--spacing-1) * 0.75)",
  space12: "calc(var(--space-8) + var(--space-4))",
  space16: "calc(var(--space-8) * 2)",
  ringSize1: "var(--spacing-0-5)",
  ringSize2: "var(--spacing-1)",
  iconStroke100: "var(--spacing-0-5)",
  iconStroke150: "calc(var(--spacing-0-5) * 1.25)",
  elevation0: "none",
  elevation1: "var(--shadow-outline-faint)",
  elevation2: "var(--shadow-outline-subtle)",
  elevation3: "var(--shadow-control)",
  progressRingDiameter: "var(--space-8)",
  progressRingStroke: "var(--ring-size-2)",
  progressRingInset: "calc(var(--space-3) / 2)",
  timerRingDiameter: "calc(var(--space-8) * 3.5)",
  timerRingStroke: "var(--ring-size-2)",
  timerRingInset: "calc(var(--space-3) / 2)",
  skeletonBg: "hsl(var(--muted) / 0.6)",
  skeletonFill: "hsl(var(--foreground) / 0.08)",
  gradientNoiseOpacity: "0.1",
  gradientNoiseOverlayOpacity: "0.06",
  spacing1: "4px",
  spacing2: "8px",
  spacing3: "12px",
  spacing4: "16px",
  spacing5: "24px",
  spacing6: "32px",
  spacing7: "48px",
  spacing8: "64px",
  radiusSm: "6px",
  radiusMd: "8px",
  radiusLg: "12px",
  radiusXl: "16px",
  radius2xl: "24px",
  radiusFull: "9999px",
};
