        {
          "id": "ai-abort-button",
          "name": "AIAbortButton",
          "description": "Abort control used to stop streaming responses with tone-aligned danger styles.",
          "tags": [
            "ai",
            "button",
            "abort"
          ],
          "kind": "primitive",
          "code": "<AIAbortButton busy onAbort={() => {}} />",
          "preview": {
            "id": "prompts:buttons:ai-abort-button"
          }
        },
        },
        {
          "id": "ai-loading-shimmer",
          "name": "AILoadingShimmer",
          "description": "Skeleton shell paired with helper text for streaming responses.",
          "tags": [
            "ai",
            "loading",
            "skeleton"
          ],
          "kind": "primitive",
          "code": "<AILoadingShimmer lines={4} />",
          "preview": {
            "id": "prompts:feedback:ai-loading-shimmer"
          }
        },
        {
          "id": "ai-error-card",
          "name": "AIErrorCard",
          "description": "Danger-toned error card with retry affordance for assistant failures.",
          "tags": [
            "ai",
            "error",
            "card"
          ],
          "kind": "primitive",
          "code": "<AIErrorCard\n  description=\"The assistant stopped before completing the draft.\"\n  hint=\"Retry to request a fresh response.\"\n  onRetry={() => {}}\n/>",
          "preview": {
            "id": "prompts:feedback:ai-error-card"
          }
      {
        "id": "ai-abort-button",
        "name": "AIAbortButton",
        "description": "Abort control used to stop streaming responses with tone-aligned danger styles.",
        "tags": [
          "ai",
          "button",
          "abort"
        ],
        "kind": "primitive",
        "code": "<AIAbortButton busy onAbort={() => {}} />",
        "preview": {
          "id": "prompts:buttons:ai-abort-button"
        }
      },
      {
        "id": "ai-loading-shimmer",
        "name": "AILoadingShimmer",
        "description": "Skeleton shell paired with helper text for streaming responses.",
        "tags": [
          "ai",
          "loading",
          "skeleton"
        ],
        "kind": "primitive",
        "code": "<AILoadingShimmer lines={4} />",
        "preview": {
          "id": "prompts:feedback:ai-loading-shimmer"
        }
      },
      {
        "id": "ai-error-card",
        "name": "AIErrorCard",
        "description": "Danger-toned error card with retry affordance for assistant failures.",
        "tags": [
          "ai",
          "error",
          "card"
        ],
        "kind": "primitive",
        "code": "<AIErrorCard\n  description=\"The assistant stopped before completing the draft.\"\n  hint=\"Retry to request a fresh response.\"\n  onRetry={() => {}}\n/>",
        "preview": {
          "id": "prompts:feedback:ai-error-card"
        }
      },
  {
    "slug": "section-buttons--entry-ai-abort-button--preview-prompts-buttons-ai-abort-button--theme-aurora",
    "previewId": "prompts:buttons:ai-abort-button",
    "entryId": "ai-abort-button",
    "entryName": "AIAbortButton",
    "sectionId": "buttons",
    "stateId": null,
    "stateName": null,
    "themeVariant": "aurora",
    "themeBackground": 0
  },
  {
    "slug": "section-buttons--entry-ai-abort-button--preview-prompts-buttons-ai-abort-button--theme-aurora--bg-1",
    "previewId": "prompts:buttons:ai-abort-button",
    "entryId": "ai-abort-button",
    "entryName": "AIAbortButton",
    "sectionId": "buttons",
    "stateId": null,
    "stateName": null,
    "themeVariant": "aurora",
    "themeBackground": 1
  },
  {
    "slug": "section-buttons--entry-ai-abort-button--preview-prompts-buttons-ai-abort-button--theme-aurora--bg-2",
    "previewId": "prompts:buttons:ai-abort-button",
    "entryId": "ai-abort-button",
    "entryName": "AIAbortButton",
    "sectionId": "buttons",
    "stateId": null,
    "stateName": null,
    "themeVariant": "aurora",
    "themeBackground": 2
  },
  {
    "slug": "section-buttons--entry-ai-abort-button--preview-prompts-buttons-ai-abort-button--theme-aurora--bg-3",
    "previewId": "prompts:buttons:ai-abort-button",
    "entryId": "ai-abort-button",
    "entryName": "AIAbortButton",
    "sectionId": "buttons",
    "stateId": null,
    "stateName": null,
    "themeVariant": "aurora",
    "themeBackground": 3
  },
  {
    "slug": "section-buttons--entry-ai-abort-button--preview-prompts-buttons-ai-abort-button--theme-aurora--bg-4",
    "previewId": "prompts:buttons:ai-abort-button",
    "entryId": "ai-abort-button",
    "entryName": "AIAbortButton",
    "sectionId": "buttons",
    "stateId": null,
    "stateName": null,
    "themeVariant": "aurora",
    "themeBackground": 4
  },
  {
    "slug": "section-buttons--entry-ai-abort-button--preview-prompts-buttons-ai-abort-button--theme-citrus",
    "previewId": "prompts:buttons:ai-abort-button",
    "entryId": "ai-abort-button",
    "entryName": "AIAbortButton",
    "sectionId": "buttons",
    "stateId": null,
    "stateName": null,
    "themeVariant": "citrus",
    "themeBackground": 0
  },
  {
    "slug": "section-buttons--entry-ai-abort-button--preview-prompts-buttons-ai-abort-button--theme-citrus--bg-1",
    "previewId": "prompts:buttons:ai-abort-button",
    "entryId": "ai-abort-button",
    "entryName": "AIAbortButton",
    "sectionId": "buttons",
    "stateId": null,
    "stateName": null,
    "themeVariant": "citrus",
    "themeBackground": 1
  },
  {
    "slug": "section-buttons--entry-ai-abort-button--preview-prompts-buttons-ai-abort-button--theme-citrus--bg-2",
    "previewId": "prompts:buttons:ai-abort-button",
    "entryId": "ai-abort-button",
    "entryName": "AIAbortButton",
    "sectionId": "buttons",
    "stateId": null,
    "stateName": null,
    "themeVariant": "citrus",
    "themeBackground": 2
  },
  {
    "slug": "section-buttons--entry-ai-abort-button--preview-prompts-buttons-ai-abort-button--theme-citrus--bg-3",
    "previewId": "prompts:buttons:ai-abort-button",
    "entryId": "ai-abort-button",
    "entryName": "AIAbortButton",
    "sectionId": "buttons",
    "stateId": null,
    "stateName": null,
    "themeVariant": "citrus",
    "themeBackground": 3
  },
  {
    "slug": "section-buttons--entry-ai-abort-button--preview-prompts-buttons-ai-abort-button--theme-citrus--bg-4",
    "previewId": "prompts:buttons:ai-abort-button",
    "entryId": "ai-abort-button",
    "entryName": "AIAbortButton",
    "sectionId": "buttons",
    "stateId": null,
    "stateName": null,
    "themeVariant": "citrus",
    "themeBackground": 4
  },
  {
    "slug": "section-buttons--entry-ai-abort-button--preview-prompts-buttons-ai-abort-button--theme-hardstuck",
    "previewId": "prompts:buttons:ai-abort-button",
    "entryId": "ai-abort-button",
    "entryName": "AIAbortButton",
    "sectionId": "buttons",
    "stateId": null,
    "stateName": null,
    "themeVariant": "hardstuck",
    "themeBackground": 0
  },
  {
    "slug": "section-buttons--entry-ai-abort-button--preview-prompts-buttons-ai-abort-button--theme-hardstuck--bg-1",
    "previewId": "prompts:buttons:ai-abort-button",
    "entryId": "ai-abort-button",
    "entryName": "AIAbortButton",
    "sectionId": "buttons",
    "stateId": null,
    "stateName": null,
    "themeVariant": "hardstuck",
    "themeBackground": 1
  },
  {
    "slug": "section-buttons--entry-ai-abort-button--preview-prompts-buttons-ai-abort-button--theme-hardstuck--bg-2",
    "previewId": "prompts:buttons:ai-abort-button",
    "entryId": "ai-abort-button",
    "entryName": "AIAbortButton",
    "sectionId": "buttons",
    "stateId": null,
    "stateName": null,
    "themeVariant": "hardstuck",
    "themeBackground": 2
  },
  {
    "slug": "section-buttons--entry-ai-abort-button--preview-prompts-buttons-ai-abort-button--theme-hardstuck--bg-3",
    "previewId": "prompts:buttons:ai-abort-button",
    "entryId": "ai-abort-button",
    "entryName": "AIAbortButton",
    "sectionId": "buttons",
    "stateId": null,
    "stateName": null,
    "themeVariant": "hardstuck",
    "themeBackground": 3
  },
  {
    "slug": "section-buttons--entry-ai-abort-button--preview-prompts-buttons-ai-abort-button--theme-hardstuck--bg-4",
    "previewId": "prompts:buttons:ai-abort-button",
    "entryId": "ai-abort-button",
    "entryName": "AIAbortButton",
    "sectionId": "buttons",
    "stateId": null,
    "stateName": null,
    "themeVariant": "hardstuck",
    "themeBackground": 4
  },
  {
    "slug": "section-buttons--entry-ai-abort-button--preview-prompts-buttons-ai-abort-button--theme-kitten",
    "previewId": "prompts:buttons:ai-abort-button",
    "entryId": "ai-abort-button",
    "entryName": "AIAbortButton",
    "sectionId": "buttons",
    "stateId": null,
    "stateName": null,
    "themeVariant": "kitten",
    "themeBackground": 0
  },
  {
    "slug": "section-buttons--entry-ai-abort-button--preview-prompts-buttons-ai-abort-button--theme-kitten--bg-1",
    "previewId": "prompts:buttons:ai-abort-button",
    "entryId": "ai-abort-button",
    "entryName": "AIAbortButton",
    "sectionId": "buttons",
    "stateId": null,
    "stateName": null,
    "themeVariant": "kitten",
    "themeBackground": 1
  },
  {
    "slug": "section-buttons--entry-ai-abort-button--preview-prompts-buttons-ai-abort-button--theme-kitten--bg-2",
    "previewId": "prompts:buttons:ai-abort-button",
    "entryId": "ai-abort-button",
    "entryName": "AIAbortButton",
    "sectionId": "buttons",
    "stateId": null,
    "stateName": null,
    "themeVariant": "kitten",
    "themeBackground": 2
  },
  {
    "slug": "section-buttons--entry-ai-abort-button--preview-prompts-buttons-ai-abort-button--theme-kitten--bg-3",
    "previewId": "prompts:buttons:ai-abort-button",
    "entryId": "ai-abort-button",
    "entryName": "AIAbortButton",
    "sectionId": "buttons",
    "stateId": null,
    "stateName": null,
    "themeVariant": "kitten",
    "themeBackground": 3
  },
  {
    "slug": "section-buttons--entry-ai-abort-button--preview-prompts-buttons-ai-abort-button--theme-kitten--bg-4",
    "previewId": "prompts:buttons:ai-abort-button",
    "entryId": "ai-abort-button",
    "entryName": "AIAbortButton",
    "sectionId": "buttons",
    "stateId": null,
    "stateName": null,
    "themeVariant": "kitten",
    "themeBackground": 4
  },
  {
    "slug": "section-buttons--entry-ai-abort-button--preview-prompts-buttons-ai-abort-button--theme-lg",
    "previewId": "prompts:buttons:ai-abort-button",
    "entryId": "ai-abort-button",
    "entryName": "AIAbortButton",
    "sectionId": "buttons",
    "stateId": null,
    "stateName": null,
    "themeVariant": "lg",
    "themeBackground": 0
  },
  {
    "slug": "section-buttons--entry-ai-abort-button--preview-prompts-buttons-ai-abort-button--theme-lg--bg-1",
    "previewId": "prompts:buttons:ai-abort-button",
    "entryId": "ai-abort-button",
    "entryName": "AIAbortButton",
    "sectionId": "buttons",
    "stateId": null,
    "stateName": null,
    "themeVariant": "lg",
    "themeBackground": 1
  },
  {
    "slug": "section-buttons--entry-ai-abort-button--preview-prompts-buttons-ai-abort-button--theme-lg--bg-2",
    "previewId": "prompts:buttons:ai-abort-button",
    "entryId": "ai-abort-button",
    "entryName": "AIAbortButton",
    "sectionId": "buttons",
    "stateId": null,
    "stateName": null,
    "themeVariant": "lg",
    "themeBackground": 2
  },
  {
    "slug": "section-buttons--entry-ai-abort-button--preview-prompts-buttons-ai-abort-button--theme-lg--bg-3",
    "previewId": "prompts:buttons:ai-abort-button",
    "entryId": "ai-abort-button",
    "entryName": "AIAbortButton",
    "sectionId": "buttons",
    "stateId": null,
    "stateName": null,
    "themeVariant": "lg",
    "themeBackground": 3
  },
  {
    "slug": "section-buttons--entry-ai-abort-button--preview-prompts-buttons-ai-abort-button--theme-lg--bg-4",
    "previewId": "prompts:buttons:ai-abort-button",
    "entryId": "ai-abort-button",
    "entryName": "AIAbortButton",
    "sectionId": "buttons",
    "stateId": null,
    "stateName": null,
    "themeVariant": "lg",
    "themeBackground": 4
  },
  {
    "slug": "section-buttons--entry-ai-abort-button--preview-prompts-buttons-ai-abort-button--theme-noir",
    "previewId": "prompts:buttons:ai-abort-button",
    "entryId": "ai-abort-button",
    "entryName": "AIAbortButton",
    "sectionId": "buttons",
    "stateId": null,
    "stateName": null,
    "themeVariant": "noir",
    "themeBackground": 0
  },
  {
    "slug": "section-buttons--entry-ai-abort-button--preview-prompts-buttons-ai-abort-button--theme-noir--bg-1",
    "previewId": "prompts:buttons:ai-abort-button",
    "entryId": "ai-abort-button",
    "entryName": "AIAbortButton",
    "sectionId": "buttons",
    "stateId": null,
    "stateName": null,
    "themeVariant": "noir",
    "themeBackground": 1
  },
  {
    "slug": "section-buttons--entry-ai-abort-button--preview-prompts-buttons-ai-abort-button--theme-noir--bg-2",
    "previewId": "prompts:buttons:ai-abort-button",
    "entryId": "ai-abort-button",
    "entryName": "AIAbortButton",
    "sectionId": "buttons",
    "stateId": null,
    "stateName": null,
    "themeVariant": "noir",
    "themeBackground": 2
  },
  {
    "slug": "section-buttons--entry-ai-abort-button--preview-prompts-buttons-ai-abort-button--theme-noir--bg-3",
    "previewId": "prompts:buttons:ai-abort-button",
    "entryId": "ai-abort-button",
    "entryName": "AIAbortButton",
    "sectionId": "buttons",
    "stateId": null,
    "stateName": null,
    "themeVariant": "noir",
    "themeBackground": 3
  },
  {
    "slug": "section-buttons--entry-ai-abort-button--preview-prompts-buttons-ai-abort-button--theme-noir--bg-4",
    "previewId": "prompts:buttons:ai-abort-button",
    "entryId": "ai-abort-button",
    "entryName": "AIAbortButton",
    "sectionId": "buttons",
    "stateId": null,
    "stateName": null,
    "themeVariant": "noir",
    "themeBackground": 4
  },
  {
    "slug": "section-buttons--entry-ai-abort-button--preview-prompts-buttons-ai-abort-button--theme-ocean",
    "previewId": "prompts:buttons:ai-abort-button",
    "entryId": "ai-abort-button",
    "entryName": "AIAbortButton",
    "sectionId": "buttons",
    "stateId": null,
    "stateName": null,
    "themeVariant": "ocean",
    "themeBackground": 0
  },
  {
    "slug": "section-buttons--entry-ai-abort-button--preview-prompts-buttons-ai-abort-button--theme-ocean--bg-1",
    "previewId": "prompts:buttons:ai-abort-button",
    "entryId": "ai-abort-button",
    "entryName": "AIAbortButton",
    "sectionId": "buttons",
    "stateId": null,
    "stateName": null,
    "themeVariant": "ocean",
    "themeBackground": 1
  },
  {
    "slug": "section-buttons--entry-ai-abort-button--preview-prompts-buttons-ai-abort-button--theme-ocean--bg-2",
    "previewId": "prompts:buttons:ai-abort-button",
    "entryId": "ai-abort-button",
    "entryName": "AIAbortButton",
    "sectionId": "buttons",
    "stateId": null,
    "stateName": null,
    "themeVariant": "ocean",
    "themeBackground": 2
  },
  {
    "slug": "section-buttons--entry-ai-abort-button--preview-prompts-buttons-ai-abort-button--theme-ocean--bg-3",
    "previewId": "prompts:buttons:ai-abort-button",
    "entryId": "ai-abort-button",
    "entryName": "AIAbortButton",
    "sectionId": "buttons",
    "stateId": null,
    "stateName": null,
    "themeVariant": "ocean",
    "themeBackground": 3
  },
  {
    "slug": "section-buttons--entry-ai-abort-button--preview-prompts-buttons-ai-abort-button--theme-ocean--bg-4",
    "previewId": "prompts:buttons:ai-abort-button",
    "entryId": "ai-abort-button",
    "entryName": "AIAbortButton",
    "sectionId": "buttons",
    "stateId": null,
    "stateName": null,
    "themeVariant": "ocean",
    "themeBackground": 4
  },
  {
    "slug": "section-feedback--entry-ai-error-card--preview-prompts-feedback-ai-error-card--theme-aurora",
    "previewId": "prompts:feedback:ai-error-card",
    "entryId": "ai-error-card",
    "entryName": "AIErrorCard",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "aurora",
    "themeBackground": 0
  },
  {
    "slug": "section-feedback--entry-ai-error-card--preview-prompts-feedback-ai-error-card--theme-aurora--bg-1",
    "previewId": "prompts:feedback:ai-error-card",
    "entryId": "ai-error-card",
    "entryName": "AIErrorCard",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "aurora",
    "themeBackground": 1
  },
  {
    "slug": "section-feedback--entry-ai-error-card--preview-prompts-feedback-ai-error-card--theme-aurora--bg-2",
    "previewId": "prompts:feedback:ai-error-card",
    "entryId": "ai-error-card",
    "entryName": "AIErrorCard",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "aurora",
    "themeBackground": 2
  },
  {
    "slug": "section-feedback--entry-ai-error-card--preview-prompts-feedback-ai-error-card--theme-aurora--bg-3",
    "previewId": "prompts:feedback:ai-error-card",
    "entryId": "ai-error-card",
    "entryName": "AIErrorCard",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "aurora",
    "themeBackground": 3
  },
  {
    "slug": "section-feedback--entry-ai-error-card--preview-prompts-feedback-ai-error-card--theme-aurora--bg-4",
    "previewId": "prompts:feedback:ai-error-card",
    "entryId": "ai-error-card",
    "entryName": "AIErrorCard",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "aurora",
    "themeBackground": 4
  },
  {
    "slug": "section-feedback--entry-ai-error-card--preview-prompts-feedback-ai-error-card--theme-citrus",
    "previewId": "prompts:feedback:ai-error-card",
    "entryId": "ai-error-card",
    "entryName": "AIErrorCard",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "citrus",
    "themeBackground": 0
  },
  {
    "slug": "section-feedback--entry-ai-error-card--preview-prompts-feedback-ai-error-card--theme-citrus--bg-1",
    "previewId": "prompts:feedback:ai-error-card",
    "entryId": "ai-error-card",
    "entryName": "AIErrorCard",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "citrus",
    "themeBackground": 1
  },
  {
    "slug": "section-feedback--entry-ai-error-card--preview-prompts-feedback-ai-error-card--theme-citrus--bg-2",
    "previewId": "prompts:feedback:ai-error-card",
    "entryId": "ai-error-card",
    "entryName": "AIErrorCard",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "citrus",
    "themeBackground": 2
  },
  {
    "slug": "section-feedback--entry-ai-error-card--preview-prompts-feedback-ai-error-card--theme-citrus--bg-3",
    "previewId": "prompts:feedback:ai-error-card",
    "entryId": "ai-error-card",
    "entryName": "AIErrorCard",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "citrus",
    "themeBackground": 3
  },
  {
    "slug": "section-feedback--entry-ai-error-card--preview-prompts-feedback-ai-error-card--theme-citrus--bg-4",
    "previewId": "prompts:feedback:ai-error-card",
    "entryId": "ai-error-card",
    "entryName": "AIErrorCard",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "citrus",
    "themeBackground": 4
  },
  {
    "slug": "section-feedback--entry-ai-error-card--preview-prompts-feedback-ai-error-card--theme-hardstuck",
    "previewId": "prompts:feedback:ai-error-card",
    "entryId": "ai-error-card",
    "entryName": "AIErrorCard",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "hardstuck",
    "themeBackground": 0
  },
  {
    "slug": "section-feedback--entry-ai-error-card--preview-prompts-feedback-ai-error-card--theme-hardstuck--bg-1",
    "previewId": "prompts:feedback:ai-error-card",
    "entryId": "ai-error-card",
    "entryName": "AIErrorCard",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "hardstuck",
    "themeBackground": 1
  },
  {
    "slug": "section-feedback--entry-ai-error-card--preview-prompts-feedback-ai-error-card--theme-hardstuck--bg-2",
    "previewId": "prompts:feedback:ai-error-card",
    "entryId": "ai-error-card",
    "entryName": "AIErrorCard",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "hardstuck",
    "themeBackground": 2
  },
  {
    "slug": "section-feedback--entry-ai-error-card--preview-prompts-feedback-ai-error-card--theme-hardstuck--bg-3",
    "previewId": "prompts:feedback:ai-error-card",
    "entryId": "ai-error-card",
    "entryName": "AIErrorCard",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "hardstuck",
    "themeBackground": 3
  },
  {
    "slug": "section-feedback--entry-ai-error-card--preview-prompts-feedback-ai-error-card--theme-hardstuck--bg-4",
    "previewId": "prompts:feedback:ai-error-card",
    "entryId": "ai-error-card",
    "entryName": "AIErrorCard",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "hardstuck",
    "themeBackground": 4
  },
  {
    "slug": "section-feedback--entry-ai-error-card--preview-prompts-feedback-ai-error-card--theme-kitten",
    "previewId": "prompts:feedback:ai-error-card",
    "entryId": "ai-error-card",
    "entryName": "AIErrorCard",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "kitten",
    "themeBackground": 0
  },
  {
    "slug": "section-feedback--entry-ai-error-card--preview-prompts-feedback-ai-error-card--theme-kitten--bg-1",
    "previewId": "prompts:feedback:ai-error-card",
    "entryId": "ai-error-card",
    "entryName": "AIErrorCard",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "kitten",
    "themeBackground": 1
  },
  {
    "slug": "section-feedback--entry-ai-error-card--preview-prompts-feedback-ai-error-card--theme-kitten--bg-2",
    "previewId": "prompts:feedback:ai-error-card",
    "entryId": "ai-error-card",
    "entryName": "AIErrorCard",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "kitten",
    "themeBackground": 2
  },
  {
    "slug": "section-feedback--entry-ai-error-card--preview-prompts-feedback-ai-error-card--theme-kitten--bg-3",
    "previewId": "prompts:feedback:ai-error-card",
    "entryId": "ai-error-card",
    "entryName": "AIErrorCard",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "kitten",
    "themeBackground": 3
  },
  {
    "slug": "section-feedback--entry-ai-error-card--preview-prompts-feedback-ai-error-card--theme-kitten--bg-4",
    "previewId": "prompts:feedback:ai-error-card",
    "entryId": "ai-error-card",
    "entryName": "AIErrorCard",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "kitten",
    "themeBackground": 4
  },
  {
    "slug": "section-feedback--entry-ai-error-card--preview-prompts-feedback-ai-error-card--theme-lg",
    "previewId": "prompts:feedback:ai-error-card",
    "entryId": "ai-error-card",
    "entryName": "AIErrorCard",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "lg",
    "themeBackground": 0
  },
  {
    "slug": "section-feedback--entry-ai-error-card--preview-prompts-feedback-ai-error-card--theme-lg--bg-1",
    "previewId": "prompts:feedback:ai-error-card",
    "entryId": "ai-error-card",
    "entryName": "AIErrorCard",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "lg",
    "themeBackground": 1
  },
  {
    "slug": "section-feedback--entry-ai-error-card--preview-prompts-feedback-ai-error-card--theme-lg--bg-2",
    "previewId": "prompts:feedback:ai-error-card",
    "entryId": "ai-error-card",
    "entryName": "AIErrorCard",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "lg",
    "themeBackground": 2
  },
  {
    "slug": "section-feedback--entry-ai-error-card--preview-prompts-feedback-ai-error-card--theme-lg--bg-3",
    "previewId": "prompts:feedback:ai-error-card",
    "entryId": "ai-error-card",
    "entryName": "AIErrorCard",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "lg",
    "themeBackground": 3
  },
  {
    "slug": "section-feedback--entry-ai-error-card--preview-prompts-feedback-ai-error-card--theme-lg--bg-4",
    "previewId": "prompts:feedback:ai-error-card",
    "entryId": "ai-error-card",
    "entryName": "AIErrorCard",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "lg",
    "themeBackground": 4
  },
  {
    "slug": "section-feedback--entry-ai-error-card--preview-prompts-feedback-ai-error-card--theme-noir",
    "previewId": "prompts:feedback:ai-error-card",
    "entryId": "ai-error-card",
    "entryName": "AIErrorCard",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "noir",
    "themeBackground": 0
  },
  {
    "slug": "section-feedback--entry-ai-error-card--preview-prompts-feedback-ai-error-card--theme-noir--bg-1",
    "previewId": "prompts:feedback:ai-error-card",
    "entryId": "ai-error-card",
    "entryName": "AIErrorCard",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "noir",
    "themeBackground": 1
  },
  {
    "slug": "section-feedback--entry-ai-error-card--preview-prompts-feedback-ai-error-card--theme-noir--bg-2",
    "previewId": "prompts:feedback:ai-error-card",
    "entryId": "ai-error-card",
    "entryName": "AIErrorCard",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "noir",
    "themeBackground": 2
  },
  {
    "slug": "section-feedback--entry-ai-error-card--preview-prompts-feedback-ai-error-card--theme-noir--bg-3",
    "previewId": "prompts:feedback:ai-error-card",
    "entryId": "ai-error-card",
    "entryName": "AIErrorCard",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "noir",
    "themeBackground": 3
  },
  {
    "slug": "section-feedback--entry-ai-error-card--preview-prompts-feedback-ai-error-card--theme-noir--bg-4",
    "previewId": "prompts:feedback:ai-error-card",
    "entryId": "ai-error-card",
    "entryName": "AIErrorCard",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "noir",
    "themeBackground": 4
  },
  {
    "slug": "section-feedback--entry-ai-error-card--preview-prompts-feedback-ai-error-card--theme-ocean",
    "previewId": "prompts:feedback:ai-error-card",
    "entryId": "ai-error-card",
    "entryName": "AIErrorCard",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "ocean",
    "themeBackground": 0
  },
  {
    "slug": "section-feedback--entry-ai-error-card--preview-prompts-feedback-ai-error-card--theme-ocean--bg-1",
    "previewId": "prompts:feedback:ai-error-card",
    "entryId": "ai-error-card",
    "entryName": "AIErrorCard",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "ocean",
    "themeBackground": 1
  },
  {
    "slug": "section-feedback--entry-ai-error-card--preview-prompts-feedback-ai-error-card--theme-ocean--bg-2",
    "previewId": "prompts:feedback:ai-error-card",
    "entryId": "ai-error-card",
    "entryName": "AIErrorCard",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "ocean",
    "themeBackground": 2
  },
  {
    "slug": "section-feedback--entry-ai-error-card--preview-prompts-feedback-ai-error-card--theme-ocean--bg-3",
    "previewId": "prompts:feedback:ai-error-card",
    "entryId": "ai-error-card",
    "entryName": "AIErrorCard",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "ocean",
    "themeBackground": 3
  },
  {
    "slug": "section-feedback--entry-ai-error-card--preview-prompts-feedback-ai-error-card--theme-ocean--bg-4",
    "previewId": "prompts:feedback:ai-error-card",
    "entryId": "ai-error-card",
    "entryName": "AIErrorCard",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "ocean",
    "themeBackground": 4
  },
  {
    "slug": "section-feedback--entry-ai-loading-shimmer--preview-prompts-feedback-ai-loading-shimmer--theme-aurora",
    "previewId": "prompts:feedback:ai-loading-shimmer",
    "entryId": "ai-loading-shimmer",
    "entryName": "AILoadingShimmer",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "aurora",
    "themeBackground": 0
  },
  {
    "slug": "section-feedback--entry-ai-loading-shimmer--preview-prompts-feedback-ai-loading-shimmer--theme-aurora--bg-1",
    "previewId": "prompts:feedback:ai-loading-shimmer",
    "entryId": "ai-loading-shimmer",
    "entryName": "AILoadingShimmer",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "aurora",
    "themeBackground": 1
  },
  {
    "slug": "section-feedback--entry-ai-loading-shimmer--preview-prompts-feedback-ai-loading-shimmer--theme-aurora--bg-2",
    "previewId": "prompts:feedback:ai-loading-shimmer",
    "entryId": "ai-loading-shimmer",
    "entryName": "AILoadingShimmer",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "aurora",
    "themeBackground": 2
  },
  {
    "slug": "section-feedback--entry-ai-loading-shimmer--preview-prompts-feedback-ai-loading-shimmer--theme-aurora--bg-3",
    "previewId": "prompts:feedback:ai-loading-shimmer",
    "entryId": "ai-loading-shimmer",
    "entryName": "AILoadingShimmer",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "aurora",
    "themeBackground": 3
  },
  {
    "slug": "section-feedback--entry-ai-loading-shimmer--preview-prompts-feedback-ai-loading-shimmer--theme-aurora--bg-4",
    "previewId": "prompts:feedback:ai-loading-shimmer",
    "entryId": "ai-loading-shimmer",
    "entryName": "AILoadingShimmer",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "aurora",
    "themeBackground": 4
  },
  {
    "slug": "section-feedback--entry-ai-loading-shimmer--preview-prompts-feedback-ai-loading-shimmer--theme-citrus",
    "previewId": "prompts:feedback:ai-loading-shimmer",
    "entryId": "ai-loading-shimmer",
    "entryName": "AILoadingShimmer",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "citrus",
    "themeBackground": 0
  },
  {
    "slug": "section-feedback--entry-ai-loading-shimmer--preview-prompts-feedback-ai-loading-shimmer--theme-citrus--bg-1",
    "previewId": "prompts:feedback:ai-loading-shimmer",
    "entryId": "ai-loading-shimmer",
    "entryName": "AILoadingShimmer",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "citrus",
    "themeBackground": 1
  },
  {
    "slug": "section-feedback--entry-ai-loading-shimmer--preview-prompts-feedback-ai-loading-shimmer--theme-citrus--bg-2",
    "previewId": "prompts:feedback:ai-loading-shimmer",
    "entryId": "ai-loading-shimmer",
    "entryName": "AILoadingShimmer",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "citrus",
    "themeBackground": 2
  },
  {
    "slug": "section-feedback--entry-ai-loading-shimmer--preview-prompts-feedback-ai-loading-shimmer--theme-citrus--bg-3",
    "previewId": "prompts:feedback:ai-loading-shimmer",
    "entryId": "ai-loading-shimmer",
    "entryName": "AILoadingShimmer",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "citrus",
    "themeBackground": 3
  },
  {
    "slug": "section-feedback--entry-ai-loading-shimmer--preview-prompts-feedback-ai-loading-shimmer--theme-citrus--bg-4",
    "previewId": "prompts:feedback:ai-loading-shimmer",
    "entryId": "ai-loading-shimmer",
    "entryName": "AILoadingShimmer",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "citrus",
    "themeBackground": 4
  },
  {
    "slug": "section-feedback--entry-ai-loading-shimmer--preview-prompts-feedback-ai-loading-shimmer--theme-hardstuck",
    "previewId": "prompts:feedback:ai-loading-shimmer",
    "entryId": "ai-loading-shimmer",
    "entryName": "AILoadingShimmer",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "hardstuck",
    "themeBackground": 0
  },
  {
    "slug": "section-feedback--entry-ai-loading-shimmer--preview-prompts-feedback-ai-loading-shimmer--theme-hardstuck--bg-1",
    "previewId": "prompts:feedback:ai-loading-shimmer",
    "entryId": "ai-loading-shimmer",
    "entryName": "AILoadingShimmer",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "hardstuck",
    "themeBackground": 1
  },
  {
    "slug": "section-feedback--entry-ai-loading-shimmer--preview-prompts-feedback-ai-loading-shimmer--theme-hardstuck--bg-2",
    "previewId": "prompts:feedback:ai-loading-shimmer",
    "entryId": "ai-loading-shimmer",
    "entryName": "AILoadingShimmer",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "hardstuck",
    "themeBackground": 2
  },
  {
    "slug": "section-feedback--entry-ai-loading-shimmer--preview-prompts-feedback-ai-loading-shimmer--theme-hardstuck--bg-3",
    "previewId": "prompts:feedback:ai-loading-shimmer",
    "entryId": "ai-loading-shimmer",
    "entryName": "AILoadingShimmer",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "hardstuck",
    "themeBackground": 3
  },
  {
    "slug": "section-feedback--entry-ai-loading-shimmer--preview-prompts-feedback-ai-loading-shimmer--theme-hardstuck--bg-4",
    "previewId": "prompts:feedback:ai-loading-shimmer",
    "entryId": "ai-loading-shimmer",
    "entryName": "AILoadingShimmer",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "hardstuck",
    "themeBackground": 4
  },
  {
    "slug": "section-feedback--entry-ai-loading-shimmer--preview-prompts-feedback-ai-loading-shimmer--theme-kitten",
    "previewId": "prompts:feedback:ai-loading-shimmer",
    "entryId": "ai-loading-shimmer",
    "entryName": "AILoadingShimmer",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "kitten",
    "themeBackground": 0
  },
  {
    "slug": "section-feedback--entry-ai-loading-shimmer--preview-prompts-feedback-ai-loading-shimmer--theme-kitten--bg-1",
    "previewId": "prompts:feedback:ai-loading-shimmer",
    "entryId": "ai-loading-shimmer",
    "entryName": "AILoadingShimmer",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "kitten",
    "themeBackground": 1
  },
  {
    "slug": "section-feedback--entry-ai-loading-shimmer--preview-prompts-feedback-ai-loading-shimmer--theme-kitten--bg-2",
    "previewId": "prompts:feedback:ai-loading-shimmer",
    "entryId": "ai-loading-shimmer",
    "entryName": "AILoadingShimmer",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "kitten",
    "themeBackground": 2
  },
  {
    "slug": "section-feedback--entry-ai-loading-shimmer--preview-prompts-feedback-ai-loading-shimmer--theme-kitten--bg-3",
    "previewId": "prompts:feedback:ai-loading-shimmer",
    "entryId": "ai-loading-shimmer",
    "entryName": "AILoadingShimmer",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "kitten",
    "themeBackground": 3
  },
  {
    "slug": "section-feedback--entry-ai-loading-shimmer--preview-prompts-feedback-ai-loading-shimmer--theme-kitten--bg-4",
    "previewId": "prompts:feedback:ai-loading-shimmer",
    "entryId": "ai-loading-shimmer",
    "entryName": "AILoadingShimmer",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "kitten",
    "themeBackground": 4
  },
  {
    "slug": "section-feedback--entry-ai-loading-shimmer--preview-prompts-feedback-ai-loading-shimmer--theme-lg",
    "previewId": "prompts:feedback:ai-loading-shimmer",
    "entryId": "ai-loading-shimmer",
    "entryName": "AILoadingShimmer",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "lg",
    "themeBackground": 0
  },
  {
    "slug": "section-feedback--entry-ai-loading-shimmer--preview-prompts-feedback-ai-loading-shimmer--theme-lg--bg-1",
    "previewId": "prompts:feedback:ai-loading-shimmer",
    "entryId": "ai-loading-shimmer",
    "entryName": "AILoadingShimmer",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "lg",
    "themeBackground": 1
  },
  {
    "slug": "section-feedback--entry-ai-loading-shimmer--preview-prompts-feedback-ai-loading-shimmer--theme-lg--bg-2",
    "previewId": "prompts:feedback:ai-loading-shimmer",
    "entryId": "ai-loading-shimmer",
    "entryName": "AILoadingShimmer",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "lg",
    "themeBackground": 2
  },
  {
    "slug": "section-feedback--entry-ai-loading-shimmer--preview-prompts-feedback-ai-loading-shimmer--theme-lg--bg-3",
    "previewId": "prompts:feedback:ai-loading-shimmer",
    "entryId": "ai-loading-shimmer",
    "entryName": "AILoadingShimmer",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "lg",
    "themeBackground": 3
  },
  {
    "slug": "section-feedback--entry-ai-loading-shimmer--preview-prompts-feedback-ai-loading-shimmer--theme-lg--bg-4",
    "previewId": "prompts:feedback:ai-loading-shimmer",
    "entryId": "ai-loading-shimmer",
    "entryName": "AILoadingShimmer",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "lg",
    "themeBackground": 4
  },
  {
    "slug": "section-feedback--entry-ai-loading-shimmer--preview-prompts-feedback-ai-loading-shimmer--theme-noir",
    "previewId": "prompts:feedback:ai-loading-shimmer",
    "entryId": "ai-loading-shimmer",
    "entryName": "AILoadingShimmer",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "noir",
    "themeBackground": 0
  },
  {
    "slug": "section-feedback--entry-ai-loading-shimmer--preview-prompts-feedback-ai-loading-shimmer--theme-noir--bg-1",
    "previewId": "prompts:feedback:ai-loading-shimmer",
    "entryId": "ai-loading-shimmer",
    "entryName": "AILoadingShimmer",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "noir",
    "themeBackground": 1
  },
  {
    "slug": "section-feedback--entry-ai-loading-shimmer--preview-prompts-feedback-ai-loading-shimmer--theme-noir--bg-2",
    "previewId": "prompts:feedback:ai-loading-shimmer",
    "entryId": "ai-loading-shimmer",
    "entryName": "AILoadingShimmer",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "noir",
    "themeBackground": 2
  },
  {
    "slug": "section-feedback--entry-ai-loading-shimmer--preview-prompts-feedback-ai-loading-shimmer--theme-noir--bg-3",
    "previewId": "prompts:feedback:ai-loading-shimmer",
    "entryId": "ai-loading-shimmer",
    "entryName": "AILoadingShimmer",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "noir",
    "themeBackground": 3
  },
  {
    "slug": "section-feedback--entry-ai-loading-shimmer--preview-prompts-feedback-ai-loading-shimmer--theme-noir--bg-4",
    "previewId": "prompts:feedback:ai-loading-shimmer",
    "entryId": "ai-loading-shimmer",
    "entryName": "AILoadingShimmer",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "noir",
    "themeBackground": 4
  },
  {
    "slug": "section-feedback--entry-ai-loading-shimmer--preview-prompts-feedback-ai-loading-shimmer--theme-ocean",
    "previewId": "prompts:feedback:ai-loading-shimmer",
    "entryId": "ai-loading-shimmer",
    "entryName": "AILoadingShimmer",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "ocean",
    "themeBackground": 0
  },
  {
    "slug": "section-feedback--entry-ai-loading-shimmer--preview-prompts-feedback-ai-loading-shimmer--theme-ocean--bg-1",
    "previewId": "prompts:feedback:ai-loading-shimmer",
    "entryId": "ai-loading-shimmer",
    "entryName": "AILoadingShimmer",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "ocean",
    "themeBackground": 1
  },
  {
    "slug": "section-feedback--entry-ai-loading-shimmer--preview-prompts-feedback-ai-loading-shimmer--theme-ocean--bg-2",
    "previewId": "prompts:feedback:ai-loading-shimmer",
    "entryId": "ai-loading-shimmer",
    "entryName": "AILoadingShimmer",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "ocean",
    "themeBackground": 2
  },
  {
    "slug": "section-feedback--entry-ai-loading-shimmer--preview-prompts-feedback-ai-loading-shimmer--theme-ocean--bg-3",
    "previewId": "prompts:feedback:ai-loading-shimmer",
    "entryId": "ai-loading-shimmer",
    "entryName": "AILoadingShimmer",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "ocean",
    "themeBackground": 3
  },
  {
    "slug": "section-feedback--entry-ai-loading-shimmer--preview-prompts-feedback-ai-loading-shimmer--theme-ocean--bg-4",
    "previewId": "prompts:feedback:ai-loading-shimmer",
    "entryId": "ai-loading-shimmer",
    "entryName": "AILoadingShimmer",
    "sectionId": "feedback",
    "stateId": null,
    "stateName": null,
    "themeVariant": "ocean",
    "themeBackground": 4
  },
      "prompts:buttons:ai-abort-button",
      "prompts:feedback:ai-loading-shimmer",
      "prompts:feedback:ai-error-card",
