// Auto-generated by scripts/build-gallery-usage.ts
// Do not edit directly.
import type { GallerySection } from "./registry";
import module0 from "../prompts/prompts.gallery";
import module1 from "../tabs/HeaderTabs.gallery";
import module2 from "../ui/Label.gallery";
import module3 from "../ui/Select.gallery";
import module4 from "../ui/layout/Header.gallery";
import module5 from "../ui/layout/TabBar.gallery";
import module6 from "../ui/primitives/Badge.gallery";
import module7 from "../ui/primitives/Button.gallery";
import module8 from "../ui/primitives/Field.gallery";
import module9 from "../ui/primitives/IconButton.gallery";
import module10 from "../ui/primitives/Input.gallery";
import module11 from "../ui/primitives/SearchBar.gallery";
import module12 from "../ui/primitives/SegmentedButton.gallery";
import module13 from "../ui/primitives/Textarea.gallery";

const modules = [
  module0,
  module1,
  module2,
  module3,
  module4,
  module5,
  module6,
  module7,
  module8,
  module9,
  module10,
  module11,
  module12,
  module13,
] satisfies readonly (GallerySection | readonly GallerySection[])[];

export default modules;
