              "type": "\"default\" | \"soft\" | \"ghost\"",
              "description": "Legacy aliases: \"primary\" → \"default\", \"secondary\" → \"soft\"."
          "code": "<div className=\"flex flex-col gap-[var(--space-4)]\">\n  <div className=\"flex flex-wrap gap-[var(--space-2)]\">\n    <Button tone=\"primary\" variant=\"default\">\n      Primary tone\n    </Button>\n    <Button tone=\"accent\" variant=\"default\">\n      Accent tone\n    </Button>\n    <Button tone=\"info\" variant=\"ghost\">\n      Info ghost\n    </Button>\n    <Button tone=\"danger\" variant=\"default\">\n      Danger primary\n    </Button>\n    <Button disabled>Disabled</Button>\n  </div>\n  <div className=\"space-y-[var(--space-2)]\">\n    <div className=\"grid grid-cols-[max-content_repeat(2,minmax(0,1fr))] gap-[var(--space-3)] text-label text-muted-foreground\">\n      <span className=\"sr-only\">Size</span>\n      <span>Leading icon</span>\n      <span>Trailing icon</span>\n    </div>\n    <div className=\"grid grid-cols-1 items-center gap-[var(--space-1)] sm:grid-cols-[max-content_repeat(2,minmax(0,1fr))]\">\n      <span className=\"text-label text-muted-foreground sm:text-ui\">Small</span>\n      <Button size=\"sm\">\n        <Plus aria-hidden />\n        Small\n      </Button>\n      <Button size=\"sm\">\n        Small\n        <Plus aria-hidden />\n      </Button>\n    </div>\n    <div className=\"grid grid-cols-1 items-center gap-[var(--space-2)] sm:grid-cols-[max-content_repeat(2,minmax(0,1fr))]\">\n      <span className=\"text-label text-muted-foreground sm:text-ui\">Medium</span>\n      <Button size=\"md\">\n        <Plus aria-hidden />\n        Medium\n      </Button>\n      <Button size=\"md\">\n        Medium\n        <Plus aria-hidden />\n      </Button>\n    </div>\n    <div className=\"grid grid-cols-1 items-center gap-[var(--space-4)] sm:grid-cols-[max-content_repeat(2,minmax(0,1fr))]\">\n      <span className=\"text-label text-muted-foreground sm:text-ui\">Large</span>\n      <Button size=\"lg\">\n        <Plus aria-hidden />\n        Large\n      </Button>\n      <Button size=\"lg\">\n        Large\n        <Plus aria-hidden />\n      </Button>\n    </div>\n    <div className=\"grid grid-cols-1 items-center gap-[calc(var(--control-h-xl)/3)] sm:grid-cols-[max-content_repeat(2,minmax(0,1fr))]\">\n      <span className=\"text-label text-muted-foreground sm:text-ui\">Extra large</span>\n      <Button size=\"xl\">\n        <Plus aria-hidden />\n        Extra large\n      </Button>\n      <Button size=\"xl\">\n        Extra large\n        <Plus aria-hidden />\n      </Button>\n    </div>\n  </div>\n  <div className=\"flex flex-wrap gap-[var(--space-2)]\">\n    <Button>Default</Button>\n    <Button className=\"bg-[--hover]\">Hover</Button>\n    <Button className=\"ring-2 ring-[var(--focus)]\">Focus</Button>\n    <Button className=\"bg-[--active]\">Active</Button>\n    <Button disabled>Disabled</Button>\n    <Button loading>Loading</Button>\n  </div>\n</div>",
              "type": "\"default\" | \"soft\" | \"ghost\"",
              "description": "Visual treatment of the button. Use \"default\" for solid, \"soft\" for tinted, and legacy aliases \"primary\"/\"secondary\" map respectively."
                  "value": "Soft"
                  "value": "Default"
                  "value": "Default variant"
                  "value": "Default hover"
                  "value": "Default active"
          "code": "<div className=\"flex flex-col gap-[var(--space-4)]\">\n  <div className=\"flex flex-wrap gap-[var(--space-2)]\">\n    <IconButton size=\"sm\" variant=\"ghost\" aria-label=\"Add item sm\">\n      <Plus />\n    </IconButton>\n    <IconButton size=\"md\" variant=\"ghost\" aria-label=\"Add item md\">\n      <Plus />\n    </IconButton>\n    <IconButton size=\"lg\" variant=\"ghost\" aria-label=\"Add item lg\">\n      <Plus />\n    </IconButton>\n    <IconButton size=\"xl\" variant=\"ghost\" aria-label=\"Add item xl\">\n      <Plus />\n    </IconButton>\n    <IconButton size=\"md\" variant=\"soft\" aria-label=\"Add item soft\">\n      <Plus />\n    </IconButton>\n    <IconButton size=\"md\" variant=\"default\" aria-label=\"Add item default\">\n      <Plus />\n    </IconButton>\n  </div>\n  <div className=\"flex flex-wrap gap-[var(--space-2)]\">\n    <IconButton aria-label=\"Default\">\n      <Plus />\n    </IconButton>\n    <IconButton className=\"bg-[--hover]\" aria-label=\"Hover\">\n      <Plus />\n    </IconButton>\n    <IconButton className=\"ring-2 ring-[var(--focus)]\" aria-label=\"Focus\">\n      <Plus />\n    </IconButton>\n    <IconButton\n      className=\"bg-[--active]\"\n      aria-pressed\n      aria-label=\"Active\"\n    >\n      <Plus />\n    </IconButton>\n    <IconButton disabled aria-label=\"Disabled\">\n      <Plus />\n    </IconButton>\n    <IconButton loading aria-label=\"Loading\">\n      <Plus />\n    </IconButton>\n  </div>\n  <div className=\"flex flex-wrap gap-[var(--space-2)]\">\n    <IconButton variant=\"default\" aria-label=\"Default variant\">\n      <Plus />\n    </IconButton>\n    <IconButton\n      className=\"bg-[--hover] shadow-[var(--shadow-neon-strong)]\"\n      variant=\"default\"\n      aria-label=\"Default hover\"\n    >\n      <Plus />\n    </IconButton>\n    <IconButton\n      className=\"bg-[--active] shadow-[var(--shadow-inset-contrast),var(--shadow-neon-soft)]\"\n      variant=\"default\"\n      aria-label=\"Default active\"\n      aria-pressed\n    >\n      <Plus />\n    </IconButton>\n  </div>\n</div>",
              "id": "default-variant",
              "name": "Default variant",
              "code": "<IconButton variant=\"default\" aria-label=\"Default variant\">\n  <Plus />\n</IconButton>",
                "id": "ui:icon-button:state:default-variant"
              "id": "default-hover",
              "name": "Default hover",
              "code": "<IconButton\n  className=\"bg-[--hover] shadow-[var(--shadow-neon-strong)]\"\n  variant=\"default\"\n  aria-label=\"Default hover\"\n>\n  <Plus />\n</IconButton>",
                "id": "ui:icon-button:state:default-hover"
              "id": "default-active",
              "name": "Default active",
              "code": "<IconButton\n  className=\"bg-[--active] shadow-[var(--shadow-inset-contrast),var(--shadow-neon-soft)]\"\n  variant=\"default\"\n  aria-label=\"Default active\"\n  aria-pressed\n>\n  <Plus />\n</IconButton>",
                "id": "ui:icon-button:state:default-active"
          "code": "<NeomorphicHeroFrame\n  as=\"header\"\n  slots={{\n    tabs: {\n      node: (\n        <TabBar\n          items={[\n            { key: \"missions\", label: \"Missions\" },\n            { key: \"briefings\", label: \"Briefings\" },\n            { key: \"archive\", label: \"Archive\", disabled: true },\n          ]}\n          value=\"missions\"\n          onValueChange={() => {}}\n          ariaLabel=\"Switch mission focus\"\n          showBaseline\n        />\n      ),\n      label: \"Switch mission focus\",\n    },\n    search: {\n      node: (\n        <SearchBar\n          value=\"\"\n          onValueChange={() => {}}\n          placeholder=\"Search mission intel…\"\n          aria-label=\"Search mission intel\"\n          loading\n        />\n      ),\n      label: \"Search mission intel\",\n    },\n    actions: {\n      node: (\n        <div className=\"flex items-center gap-[var(--space-2)]\">\n          <ThemeToggle ariaLabel=\"Toggle theme\" className=\"shrink-0\" />\n          <Button size=\"sm\" variant=\"default\" loading>\n            Deploy\n          </Button>\n          <Button size=\"sm\" variant=\"ghost\" disabled>\n            Disabled\n          </Button>\n        </div>\n      ),\n      label: \"Mission quick actions\",\n    },\n  }}\n>\n  <HeroGrid>\n    <HeroCol span={7} className=\"space-y-[var(--space-3)]\">\n      <p className=\"text-ui text-muted-foreground\">\n        Default variant uses r-card-lg radius with px-6/md:px-7/lg:px-8 tokens and aligns content to the 12-column grid.\n      </p>\n    </HeroCol>\n  </HeroGrid>\n</NeomorphicHeroFrame>\n\n<NeomorphicHeroFrame as=\"nav\" variant=\"compact\" align=\"between\">\n  <HeroGrid variant=\"compact\">\n    <HeroCol span={6}>\n      <p className=\"text-ui text-muted-foreground\">\n        Compact variant swaps to r-card-md radius with px-4/md:px-5/lg:px-6 spacing.\n      </p>\n    </HeroCol>\n  </HeroGrid>\n</NeomorphicHeroFrame>",
              "code": "<div className=\"flex items-center gap-[var(--space-2)]\">\n  <Button size=\"sm\" variant=\"default\" className=\"shadow-depth-soft\">\n    Launch event\n  </Button>\n</div>",
              "code": "<div className=\"flex items-center gap-[var(--space-2)]\">\n  <Button\n    size=\"sm\"\n    variant=\"default\"\n    className=\"shadow-depth-soft ring-2 ring-[hsl(var(--ring))] ring-offset-2 ring-offset-[hsl(var(--card)/0.7)]\"\n  >\n    Focused deploy\n  </Button>\n</div>",
              "code": "<div className=\"flex items-center gap-[var(--space-2)]\">\n  <Button size=\"sm\" variant=\"default\" loading className=\"shadow-depth-soft\">\n    Saving\n  </Button>\n</div>",
            "type": "\"default\" | \"soft\" | \"ghost\"",
            "description": "Legacy aliases: \"primary\" → \"default\", \"secondary\" → \"soft\"."
        "code": "<div className=\"flex flex-col gap-[var(--space-4)]\">\n  <div className=\"flex flex-wrap gap-[var(--space-2)]\">\n    <Button tone=\"primary\" variant=\"default\">\n      Primary tone\n    </Button>\n    <Button tone=\"accent\" variant=\"default\">\n      Accent tone\n    </Button>\n    <Button tone=\"info\" variant=\"ghost\">\n      Info ghost\n    </Button>\n    <Button tone=\"danger\" variant=\"default\">\n      Danger primary\n    </Button>\n    <Button disabled>Disabled</Button>\n  </div>\n  <div className=\"space-y-[var(--space-2)]\">\n    <div className=\"grid grid-cols-[max-content_repeat(2,minmax(0,1fr))] gap-[var(--space-3)] text-label text-muted-foreground\">\n      <span className=\"sr-only\">Size</span>\n      <span>Leading icon</span>\n      <span>Trailing icon</span>\n    </div>\n    <div className=\"grid grid-cols-1 items-center gap-[var(--space-1)] sm:grid-cols-[max-content_repeat(2,minmax(0,1fr))]\">\n      <span className=\"text-label text-muted-foreground sm:text-ui\">Small</span>\n      <Button size=\"sm\">\n        <Plus aria-hidden />\n        Small\n      </Button>\n      <Button size=\"sm\">\n        Small\n        <Plus aria-hidden />\n      </Button>\n    </div>\n    <div className=\"grid grid-cols-1 items-center gap-[var(--space-2)] sm:grid-cols-[max-content_repeat(2,minmax(0,1fr))]\">\n      <span className=\"text-label text-muted-foreground sm:text-ui\">Medium</span>\n      <Button size=\"md\">\n        <Plus aria-hidden />\n        Medium\n      </Button>\n      <Button size=\"md\">\n        Medium\n        <Plus aria-hidden />\n      </Button>\n    </div>\n    <div className=\"grid grid-cols-1 items-center gap-[var(--space-4)] sm:grid-cols-[max-content_repeat(2,minmax(0,1fr))]\">\n      <span className=\"text-label text-muted-foreground sm:text-ui\">Large</span>\n      <Button size=\"lg\">\n        <Plus aria-hidden />\n        Large\n      </Button>\n      <Button size=\"lg\">\n        Large\n        <Plus aria-hidden />\n      </Button>\n    </div>\n    <div className=\"grid grid-cols-1 items-center gap-[calc(var(--control-h-xl)/3)] sm:grid-cols-[max-content_repeat(2,minmax(0,1fr))]\">\n      <span className=\"text-label text-muted-foreground sm:text-ui\">Extra large</span>\n      <Button size=\"xl\">\n        <Plus aria-hidden />\n        Extra large\n      </Button>\n      <Button size=\"xl\">\n        Extra large\n        <Plus aria-hidden />\n      </Button>\n    </div>\n  </div>\n  <div className=\"flex flex-wrap gap-[var(--space-2)]\">\n    <Button>Default</Button>\n    <Button className=\"bg-[--hover]\">Hover</Button>\n    <Button className=\"ring-2 ring-[var(--focus)]\">Focus</Button>\n    <Button className=\"bg-[--active]\">Active</Button>\n    <Button disabled>Disabled</Button>\n    <Button loading>Loading</Button>\n  </div>\n</div>",
            "type": "\"default\" | \"soft\" | \"ghost\"",
            "description": "Visual treatment of the button. Use \"default\" for solid, \"soft\" for tinted, and legacy aliases \"primary\"/\"secondary\" map respectively."
                "value": "Soft"
                "value": "Default"
                "value": "Default variant"
                "value": "Default hover"
                "value": "Default active"
        "code": "<div className=\"flex flex-col gap-[var(--space-4)]\">\n  <div className=\"flex flex-wrap gap-[var(--space-2)]\">\n    <IconButton size=\"sm\" variant=\"ghost\" aria-label=\"Add item sm\">\n      <Plus />\n    </IconButton>\n    <IconButton size=\"md\" variant=\"ghost\" aria-label=\"Add item md\">\n      <Plus />\n    </IconButton>\n    <IconButton size=\"lg\" variant=\"ghost\" aria-label=\"Add item lg\">\n      <Plus />\n    </IconButton>\n    <IconButton size=\"xl\" variant=\"ghost\" aria-label=\"Add item xl\">\n      <Plus />\n    </IconButton>\n    <IconButton size=\"md\" variant=\"soft\" aria-label=\"Add item soft\">\n      <Plus />\n    </IconButton>\n    <IconButton size=\"md\" variant=\"default\" aria-label=\"Add item default\">\n      <Plus />\n    </IconButton>\n  </div>\n  <div className=\"flex flex-wrap gap-[var(--space-2)]\">\n    <IconButton aria-label=\"Default\">\n      <Plus />\n    </IconButton>\n    <IconButton className=\"bg-[--hover]\" aria-label=\"Hover\">\n      <Plus />\n    </IconButton>\n    <IconButton className=\"ring-2 ring-[var(--focus)]\" aria-label=\"Focus\">\n      <Plus />\n    </IconButton>\n    <IconButton\n      className=\"bg-[--active]\"\n      aria-pressed\n      aria-label=\"Active\"\n    >\n      <Plus />\n    </IconButton>\n    <IconButton disabled aria-label=\"Disabled\">\n      <Plus />\n    </IconButton>\n    <IconButton loading aria-label=\"Loading\">\n      <Plus />\n    </IconButton>\n  </div>\n  <div className=\"flex flex-wrap gap-[var(--space-2)]\">\n    <IconButton variant=\"default\" aria-label=\"Default variant\">\n      <Plus />\n    </IconButton>\n    <IconButton\n      className=\"bg-[--hover] shadow-[var(--shadow-neon-strong)]\"\n      variant=\"default\"\n      aria-label=\"Default hover\"\n    >\n      <Plus />\n    </IconButton>\n    <IconButton\n      className=\"bg-[--active] shadow-[var(--shadow-inset-contrast),var(--shadow-neon-soft)]\"\n      variant=\"default\"\n      aria-label=\"Default active\"\n      aria-pressed\n    >\n      <Plus />\n    </IconButton>\n  </div>\n</div>",
            "id": "default-variant",
            "name": "Default variant",
            "code": "<IconButton variant=\"default\" aria-label=\"Default variant\">\n  <Plus />\n</IconButton>",
              "id": "ui:icon-button:state:default-variant"
            "id": "default-hover",
            "name": "Default hover",
            "code": "<IconButton\n  className=\"bg-[--hover] shadow-[var(--shadow-neon-strong)]\"\n  variant=\"default\"\n  aria-label=\"Default hover\"\n>\n  <Plus />\n</IconButton>",
              "id": "ui:icon-button:state:default-hover"
            "id": "default-active",
            "name": "Default active",
            "code": "<IconButton\n  className=\"bg-[--active] shadow-[var(--shadow-inset-contrast),var(--shadow-neon-soft)]\"\n  variant=\"default\"\n  aria-label=\"Default active\"\n  aria-pressed\n>\n  <Plus />\n</IconButton>",
              "id": "ui:icon-button:state:default-active"
        "code": "<NeomorphicHeroFrame\n  as=\"header\"\n  slots={{\n    tabs: {\n      node: (\n        <TabBar\n          items={[\n            { key: \"missions\", label: \"Missions\" },\n            { key: \"briefings\", label: \"Briefings\" },\n            { key: \"archive\", label: \"Archive\", disabled: true },\n          ]}\n          value=\"missions\"\n          onValueChange={() => {}}\n          ariaLabel=\"Switch mission focus\"\n          showBaseline\n        />\n      ),\n      label: \"Switch mission focus\",\n    },\n    search: {\n      node: (\n        <SearchBar\n          value=\"\"\n          onValueChange={() => {}}\n          placeholder=\"Search mission intel…\"\n          aria-label=\"Search mission intel\"\n          loading\n        />\n      ),\n      label: \"Search mission intel\",\n    },\n    actions: {\n      node: (\n        <div className=\"flex items-center gap-[var(--space-2)]\">\n          <ThemeToggle ariaLabel=\"Toggle theme\" className=\"shrink-0\" />\n          <Button size=\"sm\" variant=\"default\" loading>\n            Deploy\n          </Button>\n          <Button size=\"sm\" variant=\"ghost\" disabled>\n            Disabled\n          </Button>\n        </div>\n      ),\n      label: \"Mission quick actions\",\n    },\n  }}\n>\n  <HeroGrid>\n    <HeroCol span={7} className=\"space-y-[var(--space-3)]\">\n      <p className=\"text-ui text-muted-foreground\">\n        Default variant uses r-card-lg radius with px-6/md:px-7/lg:px-8 tokens and aligns content to the 12-column grid.\n      </p>\n    </HeroCol>\n  </HeroGrid>\n</NeomorphicHeroFrame>\n\n<NeomorphicHeroFrame as=\"nav\" variant=\"compact\" align=\"between\">\n  <HeroGrid variant=\"compact\">\n    <HeroCol span={6}>\n      <p className=\"text-ui text-muted-foreground\">\n        Compact variant swaps to r-card-md radius with px-4/md:px-5/lg:px-6 spacing.\n      </p>\n    </HeroCol>\n  </HeroGrid>\n</NeomorphicHeroFrame>",
            "code": "<div className=\"flex items-center gap-[var(--space-2)]\">\n  <Button size=\"sm\" variant=\"default\" className=\"shadow-depth-soft\">\n    Launch event\n  </Button>\n</div>",
            "code": "<div className=\"flex items-center gap-[var(--space-2)]\">\n  <Button\n    size=\"sm\"\n    variant=\"default\"\n    className=\"shadow-depth-soft ring-2 ring-[hsl(var(--ring))] ring-offset-2 ring-offset-[hsl(var(--card)/0.7)]\"\n  >\n    Focused deploy\n  </Button>\n</div>",
            "code": "<div className=\"flex items-center gap-[var(--space-2)]\">\n  <Button size=\"sm\" variant=\"default\" loading className=\"shadow-depth-soft\">\n    Saving\n  </Button>\n</div>",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-active--state-default-active--theme-aurora",
    "previewId": "ui:icon-button:state:default-active",
    "stateId": "default-active",
    "stateName": "Default active",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-active--state-default-active--theme-aurora--bg-1",
    "previewId": "ui:icon-button:state:default-active",
    "stateId": "default-active",
    "stateName": "Default active",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-active--state-default-active--theme-aurora--bg-2",
    "previewId": "ui:icon-button:state:default-active",
    "stateId": "default-active",
    "stateName": "Default active",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-active--state-default-active--theme-aurora--bg-3",
    "previewId": "ui:icon-button:state:default-active",
    "stateId": "default-active",
    "stateName": "Default active",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-active--state-default-active--theme-aurora--bg-4",
    "previewId": "ui:icon-button:state:default-active",
    "stateId": "default-active",
    "stateName": "Default active",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-active--state-default-active--theme-citrus",
    "previewId": "ui:icon-button:state:default-active",
    "stateId": "default-active",
    "stateName": "Default active",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-active--state-default-active--theme-citrus--bg-1",
    "previewId": "ui:icon-button:state:default-active",
    "stateId": "default-active",
    "stateName": "Default active",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-active--state-default-active--theme-citrus--bg-2",
    "previewId": "ui:icon-button:state:default-active",
    "stateId": "default-active",
    "stateName": "Default active",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-active--state-default-active--theme-citrus--bg-3",
    "previewId": "ui:icon-button:state:default-active",
    "stateId": "default-active",
    "stateName": "Default active",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-active--state-default-active--theme-citrus--bg-4",
    "previewId": "ui:icon-button:state:default-active",
    "stateId": "default-active",
    "stateName": "Default active",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-active--state-default-active--theme-hardstuck",
    "previewId": "ui:icon-button:state:default-active",
    "stateId": "default-active",
    "stateName": "Default active",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-active--state-default-active--theme-hardstuck--bg-1",
    "previewId": "ui:icon-button:state:default-active",
    "stateId": "default-active",
    "stateName": "Default active",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-active--state-default-active--theme-hardstuck--bg-2",
    "previewId": "ui:icon-button:state:default-active",
    "stateId": "default-active",
    "stateName": "Default active",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-active--state-default-active--theme-hardstuck--bg-3",
    "previewId": "ui:icon-button:state:default-active",
    "stateId": "default-active",
    "stateName": "Default active",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-active--state-default-active--theme-hardstuck--bg-4",
    "previewId": "ui:icon-button:state:default-active",
    "stateId": "default-active",
    "stateName": "Default active",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-active--state-default-active--theme-kitten",
    "previewId": "ui:icon-button:state:default-active",
    "stateId": "default-active",
    "stateName": "Default active",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-active--state-default-active--theme-kitten--bg-1",
    "previewId": "ui:icon-button:state:default-active",
    "stateId": "default-active",
    "stateName": "Default active",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-active--state-default-active--theme-kitten--bg-2",
    "previewId": "ui:icon-button:state:default-active",
    "stateId": "default-active",
    "stateName": "Default active",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-active--state-default-active--theme-kitten--bg-3",
    "previewId": "ui:icon-button:state:default-active",
    "stateId": "default-active",
    "stateName": "Default active",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-active--state-default-active--theme-kitten--bg-4",
    "previewId": "ui:icon-button:state:default-active",
    "stateId": "default-active",
    "stateName": "Default active",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-active--state-default-active--theme-lg",
    "previewId": "ui:icon-button:state:default-active",
    "stateId": "default-active",
    "stateName": "Default active",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-active--state-default-active--theme-lg--bg-1",
    "previewId": "ui:icon-button:state:default-active",
    "stateId": "default-active",
    "stateName": "Default active",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-active--state-default-active--theme-lg--bg-2",
    "previewId": "ui:icon-button:state:default-active",
    "stateId": "default-active",
    "stateName": "Default active",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-active--state-default-active--theme-lg--bg-3",
    "previewId": "ui:icon-button:state:default-active",
    "stateId": "default-active",
    "stateName": "Default active",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-active--state-default-active--theme-lg--bg-4",
    "previewId": "ui:icon-button:state:default-active",
    "stateId": "default-active",
    "stateName": "Default active",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-active--state-default-active--theme-noir",
    "previewId": "ui:icon-button:state:default-active",
    "stateId": "default-active",
    "stateName": "Default active",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-active--state-default-active--theme-noir--bg-1",
    "previewId": "ui:icon-button:state:default-active",
    "stateId": "default-active",
    "stateName": "Default active",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-active--state-default-active--theme-noir--bg-2",
    "previewId": "ui:icon-button:state:default-active",
    "stateId": "default-active",
    "stateName": "Default active",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-active--state-default-active--theme-noir--bg-3",
    "previewId": "ui:icon-button:state:default-active",
    "stateId": "default-active",
    "stateName": "Default active",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-active--state-default-active--theme-noir--bg-4",
    "previewId": "ui:icon-button:state:default-active",
    "stateId": "default-active",
    "stateName": "Default active",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-active--state-default-active--theme-ocean",
    "previewId": "ui:icon-button:state:default-active",
    "stateId": "default-active",
    "stateName": "Default active",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-active--state-default-active--theme-ocean--bg-1",
    "previewId": "ui:icon-button:state:default-active",
    "stateId": "default-active",
    "stateName": "Default active",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-active--state-default-active--theme-ocean--bg-2",
    "previewId": "ui:icon-button:state:default-active",
    "stateId": "default-active",
    "stateName": "Default active",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-active--state-default-active--theme-ocean--bg-3",
    "previewId": "ui:icon-button:state:default-active",
    "stateId": "default-active",
    "stateName": "Default active",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-active--state-default-active--theme-ocean--bg-4",
    "previewId": "ui:icon-button:state:default-active",
    "stateId": "default-active",
    "stateName": "Default active",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-hover--state-default-hover--theme-aurora",
    "previewId": "ui:icon-button:state:default-hover",
    "stateId": "default-hover",
    "stateName": "Default hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-hover--state-default-hover--theme-aurora--bg-1",
    "previewId": "ui:icon-button:state:default-hover",
    "stateId": "default-hover",
    "stateName": "Default hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-hover--state-default-hover--theme-aurora--bg-2",
    "previewId": "ui:icon-button:state:default-hover",
    "stateId": "default-hover",
    "stateName": "Default hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-hover--state-default-hover--theme-aurora--bg-3",
    "previewId": "ui:icon-button:state:default-hover",
    "stateId": "default-hover",
    "stateName": "Default hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-hover--state-default-hover--theme-aurora--bg-4",
    "previewId": "ui:icon-button:state:default-hover",
    "stateId": "default-hover",
    "stateName": "Default hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-hover--state-default-hover--theme-citrus",
    "previewId": "ui:icon-button:state:default-hover",
    "stateId": "default-hover",
    "stateName": "Default hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-hover--state-default-hover--theme-citrus--bg-1",
    "previewId": "ui:icon-button:state:default-hover",
    "stateId": "default-hover",
    "stateName": "Default hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-hover--state-default-hover--theme-citrus--bg-2",
    "previewId": "ui:icon-button:state:default-hover",
    "stateId": "default-hover",
    "stateName": "Default hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-hover--state-default-hover--theme-citrus--bg-3",
    "previewId": "ui:icon-button:state:default-hover",
    "stateId": "default-hover",
    "stateName": "Default hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-hover--state-default-hover--theme-citrus--bg-4",
    "previewId": "ui:icon-button:state:default-hover",
    "stateId": "default-hover",
    "stateName": "Default hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-hover--state-default-hover--theme-hardstuck",
    "previewId": "ui:icon-button:state:default-hover",
    "stateId": "default-hover",
    "stateName": "Default hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-hover--state-default-hover--theme-hardstuck--bg-1",
    "previewId": "ui:icon-button:state:default-hover",
    "stateId": "default-hover",
    "stateName": "Default hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-hover--state-default-hover--theme-hardstuck--bg-2",
    "previewId": "ui:icon-button:state:default-hover",
    "stateId": "default-hover",
    "stateName": "Default hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-hover--state-default-hover--theme-hardstuck--bg-3",
    "previewId": "ui:icon-button:state:default-hover",
    "stateId": "default-hover",
    "stateName": "Default hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-hover--state-default-hover--theme-hardstuck--bg-4",
    "previewId": "ui:icon-button:state:default-hover",
    "stateId": "default-hover",
    "stateName": "Default hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-hover--state-default-hover--theme-kitten",
    "previewId": "ui:icon-button:state:default-hover",
    "stateId": "default-hover",
    "stateName": "Default hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-hover--state-default-hover--theme-kitten--bg-1",
    "previewId": "ui:icon-button:state:default-hover",
    "stateId": "default-hover",
    "stateName": "Default hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-hover--state-default-hover--theme-kitten--bg-2",
    "previewId": "ui:icon-button:state:default-hover",
    "stateId": "default-hover",
    "stateName": "Default hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-hover--state-default-hover--theme-kitten--bg-3",
    "previewId": "ui:icon-button:state:default-hover",
    "stateId": "default-hover",
    "stateName": "Default hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-hover--state-default-hover--theme-kitten--bg-4",
    "previewId": "ui:icon-button:state:default-hover",
    "stateId": "default-hover",
    "stateName": "Default hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-hover--state-default-hover--theme-lg",
    "previewId": "ui:icon-button:state:default-hover",
    "stateId": "default-hover",
    "stateName": "Default hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-hover--state-default-hover--theme-lg--bg-1",
    "previewId": "ui:icon-button:state:default-hover",
    "stateId": "default-hover",
    "stateName": "Default hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-hover--state-default-hover--theme-lg--bg-2",
    "previewId": "ui:icon-button:state:default-hover",
    "stateId": "default-hover",
    "stateName": "Default hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-hover--state-default-hover--theme-lg--bg-3",
    "previewId": "ui:icon-button:state:default-hover",
    "stateId": "default-hover",
    "stateName": "Default hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-hover--state-default-hover--theme-lg--bg-4",
    "previewId": "ui:icon-button:state:default-hover",
    "stateId": "default-hover",
    "stateName": "Default hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-hover--state-default-hover--theme-noir",
    "previewId": "ui:icon-button:state:default-hover",
    "stateId": "default-hover",
    "stateName": "Default hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-hover--state-default-hover--theme-noir--bg-1",
    "previewId": "ui:icon-button:state:default-hover",
    "stateId": "default-hover",
    "stateName": "Default hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-hover--state-default-hover--theme-noir--bg-2",
    "previewId": "ui:icon-button:state:default-hover",
    "stateId": "default-hover",
    "stateName": "Default hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-hover--state-default-hover--theme-noir--bg-3",
    "previewId": "ui:icon-button:state:default-hover",
    "stateId": "default-hover",
    "stateName": "Default hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-hover--state-default-hover--theme-noir--bg-4",
    "previewId": "ui:icon-button:state:default-hover",
    "stateId": "default-hover",
    "stateName": "Default hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-hover--state-default-hover--theme-ocean",
    "previewId": "ui:icon-button:state:default-hover",
    "stateId": "default-hover",
    "stateName": "Default hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-hover--state-default-hover--theme-ocean--bg-1",
    "previewId": "ui:icon-button:state:default-hover",
    "stateId": "default-hover",
    "stateName": "Default hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-hover--state-default-hover--theme-ocean--bg-2",
    "previewId": "ui:icon-button:state:default-hover",
    "stateId": "default-hover",
    "stateName": "Default hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-hover--state-default-hover--theme-ocean--bg-3",
    "previewId": "ui:icon-button:state:default-hover",
    "stateId": "default-hover",
    "stateName": "Default hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-hover--state-default-hover--theme-ocean--bg-4",
    "previewId": "ui:icon-button:state:default-hover",
    "stateId": "default-hover",
    "stateName": "Default hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-variant--state-default-variant--theme-aurora",
    "previewId": "ui:icon-button:state:default-variant",
    "stateId": "default-variant",
    "stateName": "Default variant",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-variant--state-default-variant--theme-aurora--bg-1",
    "previewId": "ui:icon-button:state:default-variant",
    "stateId": "default-variant",
    "stateName": "Default variant",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-variant--state-default-variant--theme-aurora--bg-2",
    "previewId": "ui:icon-button:state:default-variant",
    "stateId": "default-variant",
    "stateName": "Default variant",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-variant--state-default-variant--theme-aurora--bg-3",
    "previewId": "ui:icon-button:state:default-variant",
    "stateId": "default-variant",
    "stateName": "Default variant",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-variant--state-default-variant--theme-aurora--bg-4",
    "previewId": "ui:icon-button:state:default-variant",
    "stateId": "default-variant",
    "stateName": "Default variant",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-variant--state-default-variant--theme-citrus",
    "previewId": "ui:icon-button:state:default-variant",
    "stateId": "default-variant",
    "stateName": "Default variant",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-variant--state-default-variant--theme-citrus--bg-1",
    "previewId": "ui:icon-button:state:default-variant",
    "stateId": "default-variant",
    "stateName": "Default variant",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-variant--state-default-variant--theme-citrus--bg-2",
    "previewId": "ui:icon-button:state:default-variant",
    "stateId": "default-variant",
    "stateName": "Default variant",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-variant--state-default-variant--theme-citrus--bg-3",
    "previewId": "ui:icon-button:state:default-variant",
    "stateId": "default-variant",
    "stateName": "Default variant",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-variant--state-default-variant--theme-citrus--bg-4",
    "previewId": "ui:icon-button:state:default-variant",
    "stateId": "default-variant",
    "stateName": "Default variant",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-variant--state-default-variant--theme-hardstuck",
    "previewId": "ui:icon-button:state:default-variant",
    "stateId": "default-variant",
    "stateName": "Default variant",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-variant--state-default-variant--theme-hardstuck--bg-1",
    "previewId": "ui:icon-button:state:default-variant",
    "stateId": "default-variant",
    "stateName": "Default variant",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-variant--state-default-variant--theme-hardstuck--bg-2",
    "previewId": "ui:icon-button:state:default-variant",
    "stateId": "default-variant",
    "stateName": "Default variant",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-variant--state-default-variant--theme-hardstuck--bg-3",
    "previewId": "ui:icon-button:state:default-variant",
    "stateId": "default-variant",
    "stateName": "Default variant",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-variant--state-default-variant--theme-hardstuck--bg-4",
    "previewId": "ui:icon-button:state:default-variant",
    "stateId": "default-variant",
    "stateName": "Default variant",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-variant--state-default-variant--theme-kitten",
    "previewId": "ui:icon-button:state:default-variant",
    "stateId": "default-variant",
    "stateName": "Default variant",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-variant--state-default-variant--theme-kitten--bg-1",
    "previewId": "ui:icon-button:state:default-variant",
    "stateId": "default-variant",
    "stateName": "Default variant",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-variant--state-default-variant--theme-kitten--bg-2",
    "previewId": "ui:icon-button:state:default-variant",
    "stateId": "default-variant",
    "stateName": "Default variant",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-variant--state-default-variant--theme-kitten--bg-3",
    "previewId": "ui:icon-button:state:default-variant",
    "stateId": "default-variant",
    "stateName": "Default variant",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-variant--state-default-variant--theme-kitten--bg-4",
    "previewId": "ui:icon-button:state:default-variant",
    "stateId": "default-variant",
    "stateName": "Default variant",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-variant--state-default-variant--theme-lg",
    "previewId": "ui:icon-button:state:default-variant",
    "stateId": "default-variant",
    "stateName": "Default variant",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-variant--state-default-variant--theme-lg--bg-1",
    "previewId": "ui:icon-button:state:default-variant",
    "stateId": "default-variant",
    "stateName": "Default variant",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-variant--state-default-variant--theme-lg--bg-2",
    "previewId": "ui:icon-button:state:default-variant",
    "stateId": "default-variant",
    "stateName": "Default variant",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-variant--state-default-variant--theme-lg--bg-3",
    "previewId": "ui:icon-button:state:default-variant",
    "stateId": "default-variant",
    "stateName": "Default variant",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-variant--state-default-variant--theme-lg--bg-4",
    "previewId": "ui:icon-button:state:default-variant",
    "stateId": "default-variant",
    "stateName": "Default variant",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-variant--state-default-variant--theme-noir",
    "previewId": "ui:icon-button:state:default-variant",
    "stateId": "default-variant",
    "stateName": "Default variant",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-variant--state-default-variant--theme-noir--bg-1",
    "previewId": "ui:icon-button:state:default-variant",
    "stateId": "default-variant",
    "stateName": "Default variant",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-variant--state-default-variant--theme-noir--bg-2",
    "previewId": "ui:icon-button:state:default-variant",
    "stateId": "default-variant",
    "stateName": "Default variant",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-variant--state-default-variant--theme-noir--bg-3",
    "previewId": "ui:icon-button:state:default-variant",
    "stateId": "default-variant",
    "stateName": "Default variant",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-variant--state-default-variant--theme-noir--bg-4",
    "previewId": "ui:icon-button:state:default-variant",
    "stateId": "default-variant",
    "stateName": "Default variant",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-variant--state-default-variant--theme-ocean",
    "previewId": "ui:icon-button:state:default-variant",
    "stateId": "default-variant",
    "stateName": "Default variant",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-variant--state-default-variant--theme-ocean--bg-1",
    "previewId": "ui:icon-button:state:default-variant",
    "stateId": "default-variant",
    "stateName": "Default variant",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-variant--state-default-variant--theme-ocean--bg-2",
    "previewId": "ui:icon-button:state:default-variant",
    "stateId": "default-variant",
    "stateName": "Default variant",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-variant--state-default-variant--theme-ocean--bg-3",
    "previewId": "ui:icon-button:state:default-variant",
    "stateId": "default-variant",
    "stateName": "Default variant",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-default-variant--state-default-variant--theme-ocean--bg-4",
    "previewId": "ui:icon-button:state:default-variant",
    "stateId": "default-variant",
    "stateName": "Default variant",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-disabled--state-disabled--theme-aurora",
    "previewId": "ui:icon-button:state:disabled",
    "stateId": "disabled",
    "stateName": "Disabled",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-disabled--state-disabled--theme-aurora--bg-1",
    "previewId": "ui:icon-button:state:disabled",
    "stateId": "disabled",
    "stateName": "Disabled",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-disabled--state-disabled--theme-aurora--bg-2",
    "previewId": "ui:icon-button:state:disabled",
    "stateId": "disabled",
    "stateName": "Disabled",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-disabled--state-disabled--theme-aurora--bg-3",
    "previewId": "ui:icon-button:state:disabled",
    "stateId": "disabled",
    "stateName": "Disabled",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-disabled--state-disabled--theme-aurora--bg-4",
    "previewId": "ui:icon-button:state:disabled",
    "stateId": "disabled",
    "stateName": "Disabled",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-disabled--state-disabled--theme-citrus",
    "previewId": "ui:icon-button:state:disabled",
    "stateId": "disabled",
    "stateName": "Disabled",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-disabled--state-disabled--theme-citrus--bg-1",
    "previewId": "ui:icon-button:state:disabled",
    "stateId": "disabled",
    "stateName": "Disabled",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-disabled--state-disabled--theme-citrus--bg-2",
    "previewId": "ui:icon-button:state:disabled",
    "stateId": "disabled",
    "stateName": "Disabled",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-disabled--state-disabled--theme-citrus--bg-3",
    "previewId": "ui:icon-button:state:disabled",
    "stateId": "disabled",
    "stateName": "Disabled",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-disabled--state-disabled--theme-citrus--bg-4",
    "previewId": "ui:icon-button:state:disabled",
    "stateId": "disabled",
    "stateName": "Disabled",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-disabled--state-disabled--theme-hardstuck",
    "previewId": "ui:icon-button:state:disabled",
    "stateId": "disabled",
    "stateName": "Disabled",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-disabled--state-disabled--theme-hardstuck--bg-1",
    "previewId": "ui:icon-button:state:disabled",
    "stateId": "disabled",
    "stateName": "Disabled",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-disabled--state-disabled--theme-hardstuck--bg-2",
    "previewId": "ui:icon-button:state:disabled",
    "stateId": "disabled",
    "stateName": "Disabled",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-disabled--state-disabled--theme-hardstuck--bg-3",
    "previewId": "ui:icon-button:state:disabled",
    "stateId": "disabled",
    "stateName": "Disabled",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-disabled--state-disabled--theme-hardstuck--bg-4",
    "previewId": "ui:icon-button:state:disabled",
    "stateId": "disabled",
    "stateName": "Disabled",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-disabled--state-disabled--theme-kitten",
    "previewId": "ui:icon-button:state:disabled",
    "stateId": "disabled",
    "stateName": "Disabled",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-disabled--state-disabled--theme-kitten--bg-1",
    "previewId": "ui:icon-button:state:disabled",
    "stateId": "disabled",
    "stateName": "Disabled",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-disabled--state-disabled--theme-kitten--bg-2",
    "previewId": "ui:icon-button:state:disabled",
    "stateId": "disabled",
    "stateName": "Disabled",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-disabled--state-disabled--theme-kitten--bg-3",
    "previewId": "ui:icon-button:state:disabled",
    "stateId": "disabled",
    "stateName": "Disabled",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-disabled--state-disabled--theme-kitten--bg-4",
    "previewId": "ui:icon-button:state:disabled",
    "stateId": "disabled",
    "stateName": "Disabled",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-disabled--state-disabled--theme-lg",
    "previewId": "ui:icon-button:state:disabled",
    "stateId": "disabled",
    "stateName": "Disabled",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-disabled--state-disabled--theme-lg--bg-1",
    "previewId": "ui:icon-button:state:disabled",
    "stateId": "disabled",
    "stateName": "Disabled",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-disabled--state-disabled--theme-lg--bg-2",
    "previewId": "ui:icon-button:state:disabled",
    "stateId": "disabled",
    "stateName": "Disabled",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-disabled--state-disabled--theme-lg--bg-3",
    "previewId": "ui:icon-button:state:disabled",
    "stateId": "disabled",
    "stateName": "Disabled",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-disabled--state-disabled--theme-lg--bg-4",
    "previewId": "ui:icon-button:state:disabled",
    "stateId": "disabled",
    "stateName": "Disabled",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-disabled--state-disabled--theme-noir",
    "previewId": "ui:icon-button:state:disabled",
    "stateId": "disabled",
    "stateName": "Disabled",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-disabled--state-disabled--theme-noir--bg-1",
    "previewId": "ui:icon-button:state:disabled",
    "stateId": "disabled",
    "stateName": "Disabled",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-disabled--state-disabled--theme-noir--bg-2",
    "previewId": "ui:icon-button:state:disabled",
    "stateId": "disabled",
    "stateName": "Disabled",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-disabled--state-disabled--theme-noir--bg-3",
    "previewId": "ui:icon-button:state:disabled",
    "stateId": "disabled",
    "stateName": "Disabled",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-disabled--state-disabled--theme-noir--bg-4",
    "previewId": "ui:icon-button:state:disabled",
    "stateId": "disabled",
    "stateName": "Disabled",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-disabled--state-disabled--theme-ocean",
    "previewId": "ui:icon-button:state:disabled",
    "stateId": "disabled",
    "stateName": "Disabled",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-disabled--state-disabled--theme-ocean--bg-1",
    "previewId": "ui:icon-button:state:disabled",
    "stateId": "disabled",
    "stateName": "Disabled",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-disabled--state-disabled--theme-ocean--bg-2",
    "previewId": "ui:icon-button:state:disabled",
    "stateId": "disabled",
    "stateName": "Disabled",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-disabled--state-disabled--theme-ocean--bg-3",
    "previewId": "ui:icon-button:state:disabled",
    "stateId": "disabled",
    "stateName": "Disabled",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-disabled--state-disabled--theme-ocean--bg-4",
    "previewId": "ui:icon-button:state:disabled",
    "stateId": "disabled",
    "stateName": "Disabled",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-focus--state-focus--theme-aurora",
    "previewId": "ui:icon-button:state:focus",
    "stateId": "focus",
    "stateName": "Focus",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-focus--state-focus--theme-aurora--bg-1",
    "previewId": "ui:icon-button:state:focus",
    "stateId": "focus",
    "stateName": "Focus",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-focus--state-focus--theme-aurora--bg-2",
    "previewId": "ui:icon-button:state:focus",
    "stateId": "focus",
    "stateName": "Focus",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-focus--state-focus--theme-aurora--bg-3",
    "previewId": "ui:icon-button:state:focus",
    "stateId": "focus",
    "stateName": "Focus",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-focus--state-focus--theme-aurora--bg-4",
    "previewId": "ui:icon-button:state:focus",
    "stateId": "focus",
    "stateName": "Focus",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-focus--state-focus--theme-citrus",
    "previewId": "ui:icon-button:state:focus",
    "stateId": "focus",
    "stateName": "Focus",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-focus--state-focus--theme-citrus--bg-1",
    "previewId": "ui:icon-button:state:focus",
    "stateId": "focus",
    "stateName": "Focus",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-focus--state-focus--theme-citrus--bg-2",
    "previewId": "ui:icon-button:state:focus",
    "stateId": "focus",
    "stateName": "Focus",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-focus--state-focus--theme-citrus--bg-3",
    "previewId": "ui:icon-button:state:focus",
    "stateId": "focus",
    "stateName": "Focus",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-focus--state-focus--theme-citrus--bg-4",
    "previewId": "ui:icon-button:state:focus",
    "stateId": "focus",
    "stateName": "Focus",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-focus--state-focus--theme-hardstuck",
    "previewId": "ui:icon-button:state:focus",
    "stateId": "focus",
    "stateName": "Focus",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-focus--state-focus--theme-hardstuck--bg-1",
    "previewId": "ui:icon-button:state:focus",
    "stateId": "focus",
    "stateName": "Focus",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-focus--state-focus--theme-hardstuck--bg-2",
    "previewId": "ui:icon-button:state:focus",
    "stateId": "focus",
    "stateName": "Focus",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-focus--state-focus--theme-hardstuck--bg-3",
    "previewId": "ui:icon-button:state:focus",
    "stateId": "focus",
    "stateName": "Focus",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-focus--state-focus--theme-hardstuck--bg-4",
    "previewId": "ui:icon-button:state:focus",
    "stateId": "focus",
    "stateName": "Focus",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-focus--state-focus--theme-kitten",
    "previewId": "ui:icon-button:state:focus",
    "stateId": "focus",
    "stateName": "Focus",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-focus--state-focus--theme-kitten--bg-1",
    "previewId": "ui:icon-button:state:focus",
    "stateId": "focus",
    "stateName": "Focus",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-focus--state-focus--theme-kitten--bg-2",
    "previewId": "ui:icon-button:state:focus",
    "stateId": "focus",
    "stateName": "Focus",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-focus--state-focus--theme-kitten--bg-3",
    "previewId": "ui:icon-button:state:focus",
    "stateId": "focus",
    "stateName": "Focus",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-focus--state-focus--theme-kitten--bg-4",
    "previewId": "ui:icon-button:state:focus",
    "stateId": "focus",
    "stateName": "Focus",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-focus--state-focus--theme-lg",
    "previewId": "ui:icon-button:state:focus",
    "stateId": "focus",
    "stateName": "Focus",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-focus--state-focus--theme-lg--bg-1",
    "previewId": "ui:icon-button:state:focus",
    "stateId": "focus",
    "stateName": "Focus",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-focus--state-focus--theme-lg--bg-2",
    "previewId": "ui:icon-button:state:focus",
    "stateId": "focus",
    "stateName": "Focus",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-focus--state-focus--theme-lg--bg-3",
    "previewId": "ui:icon-button:state:focus",
    "stateId": "focus",
    "stateName": "Focus",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-focus--state-focus--theme-lg--bg-4",
    "previewId": "ui:icon-button:state:focus",
    "stateId": "focus",
    "stateName": "Focus",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-focus--state-focus--theme-noir",
    "previewId": "ui:icon-button:state:focus",
    "stateId": "focus",
    "stateName": "Focus",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-focus--state-focus--theme-noir--bg-1",
    "previewId": "ui:icon-button:state:focus",
    "stateId": "focus",
    "stateName": "Focus",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-focus--state-focus--theme-noir--bg-2",
    "previewId": "ui:icon-button:state:focus",
    "stateId": "focus",
    "stateName": "Focus",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-focus--state-focus--theme-noir--bg-3",
    "previewId": "ui:icon-button:state:focus",
    "stateId": "focus",
    "stateName": "Focus",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-focus--state-focus--theme-noir--bg-4",
    "previewId": "ui:icon-button:state:focus",
    "stateId": "focus",
    "stateName": "Focus",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-focus--state-focus--theme-ocean",
    "previewId": "ui:icon-button:state:focus",
    "stateId": "focus",
    "stateName": "Focus",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-focus--state-focus--theme-ocean--bg-1",
    "previewId": "ui:icon-button:state:focus",
    "stateId": "focus",
    "stateName": "Focus",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-focus--state-focus--theme-ocean--bg-2",
    "previewId": "ui:icon-button:state:focus",
    "stateId": "focus",
    "stateName": "Focus",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-focus--state-focus--theme-ocean--bg-3",
    "previewId": "ui:icon-button:state:focus",
    "stateId": "focus",
    "stateName": "Focus",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-focus--state-focus--theme-ocean--bg-4",
    "previewId": "ui:icon-button:state:focus",
    "stateId": "focus",
    "stateName": "Focus",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-glitch--state-glitch--theme-aurora",
    "previewId": "ui:icon-button:state:glitch",
    "stateId": "glitch",
    "stateName": "Glitch overlay",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-glitch--state-glitch--theme-aurora--bg-1",
    "previewId": "ui:icon-button:state:glitch",
    "stateId": "glitch",
    "stateName": "Glitch overlay",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-glitch--state-glitch--theme-aurora--bg-2",
    "previewId": "ui:icon-button:state:glitch",
    "stateId": "glitch",
    "stateName": "Glitch overlay",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-glitch--state-glitch--theme-aurora--bg-3",
    "previewId": "ui:icon-button:state:glitch",
    "stateId": "glitch",
    "stateName": "Glitch overlay",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-glitch--state-glitch--theme-aurora--bg-4",
    "previewId": "ui:icon-button:state:glitch",
    "stateId": "glitch",
    "stateName": "Glitch overlay",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-glitch--state-glitch--theme-citrus",
    "previewId": "ui:icon-button:state:glitch",
    "stateId": "glitch",
    "stateName": "Glitch overlay",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-glitch--state-glitch--theme-citrus--bg-1",
    "previewId": "ui:icon-button:state:glitch",
    "stateId": "glitch",
    "stateName": "Glitch overlay",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-glitch--state-glitch--theme-citrus--bg-2",
    "previewId": "ui:icon-button:state:glitch",
    "stateId": "glitch",
    "stateName": "Glitch overlay",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-glitch--state-glitch--theme-citrus--bg-3",
    "previewId": "ui:icon-button:state:glitch",
    "stateId": "glitch",
    "stateName": "Glitch overlay",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-glitch--state-glitch--theme-citrus--bg-4",
    "previewId": "ui:icon-button:state:glitch",
    "stateId": "glitch",
    "stateName": "Glitch overlay",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-glitch--state-glitch--theme-hardstuck",
    "previewId": "ui:icon-button:state:glitch",
    "stateId": "glitch",
    "stateName": "Glitch overlay",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-glitch--state-glitch--theme-hardstuck--bg-1",
    "previewId": "ui:icon-button:state:glitch",
    "stateId": "glitch",
    "stateName": "Glitch overlay",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-glitch--state-glitch--theme-hardstuck--bg-2",
    "previewId": "ui:icon-button:state:glitch",
    "stateId": "glitch",
    "stateName": "Glitch overlay",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-glitch--state-glitch--theme-hardstuck--bg-3",
    "previewId": "ui:icon-button:state:glitch",
    "stateId": "glitch",
    "stateName": "Glitch overlay",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-glitch--state-glitch--theme-hardstuck--bg-4",
    "previewId": "ui:icon-button:state:glitch",
    "stateId": "glitch",
    "stateName": "Glitch overlay",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-glitch--state-glitch--theme-kitten",
    "previewId": "ui:icon-button:state:glitch",
    "stateId": "glitch",
    "stateName": "Glitch overlay",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-glitch--state-glitch--theme-kitten--bg-1",
    "previewId": "ui:icon-button:state:glitch",
    "stateId": "glitch",
    "stateName": "Glitch overlay",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-glitch--state-glitch--theme-kitten--bg-2",
    "previewId": "ui:icon-button:state:glitch",
    "stateId": "glitch",
    "stateName": "Glitch overlay",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-glitch--state-glitch--theme-kitten--bg-3",
    "previewId": "ui:icon-button:state:glitch",
    "stateId": "glitch",
    "stateName": "Glitch overlay",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-glitch--state-glitch--theme-kitten--bg-4",
    "previewId": "ui:icon-button:state:glitch",
    "stateId": "glitch",
    "stateName": "Glitch overlay",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-glitch--state-glitch--theme-lg",
    "previewId": "ui:icon-button:state:glitch",
    "stateId": "glitch",
    "stateName": "Glitch overlay",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-glitch--state-glitch--theme-lg--bg-1",
    "previewId": "ui:icon-button:state:glitch",
    "stateId": "glitch",
    "stateName": "Glitch overlay",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-glitch--state-glitch--theme-lg--bg-2",
    "previewId": "ui:icon-button:state:glitch",
    "stateId": "glitch",
    "stateName": "Glitch overlay",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-glitch--state-glitch--theme-lg--bg-3",
    "previewId": "ui:icon-button:state:glitch",
    "stateId": "glitch",
    "stateName": "Glitch overlay",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-glitch--state-glitch--theme-lg--bg-4",
    "previewId": "ui:icon-button:state:glitch",
    "stateId": "glitch",
    "stateName": "Glitch overlay",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-glitch--state-glitch--theme-noir",
    "previewId": "ui:icon-button:state:glitch",
    "stateId": "glitch",
    "stateName": "Glitch overlay",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-glitch--state-glitch--theme-noir--bg-1",
    "previewId": "ui:icon-button:state:glitch",
    "stateId": "glitch",
    "stateName": "Glitch overlay",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-glitch--state-glitch--theme-noir--bg-2",
    "previewId": "ui:icon-button:state:glitch",
    "stateId": "glitch",
    "stateName": "Glitch overlay",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-glitch--state-glitch--theme-noir--bg-3",
    "previewId": "ui:icon-button:state:glitch",
    "stateId": "glitch",
    "stateName": "Glitch overlay",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-glitch--state-glitch--theme-noir--bg-4",
    "previewId": "ui:icon-button:state:glitch",
    "stateId": "glitch",
    "stateName": "Glitch overlay",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-glitch--state-glitch--theme-ocean",
    "previewId": "ui:icon-button:state:glitch",
    "stateId": "glitch",
    "stateName": "Glitch overlay",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-glitch--state-glitch--theme-ocean--bg-1",
    "previewId": "ui:icon-button:state:glitch",
    "stateId": "glitch",
    "stateName": "Glitch overlay",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-glitch--state-glitch--theme-ocean--bg-2",
    "previewId": "ui:icon-button:state:glitch",
    "stateId": "glitch",
    "stateName": "Glitch overlay",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-glitch--state-glitch--theme-ocean--bg-3",
    "previewId": "ui:icon-button:state:glitch",
    "stateId": "glitch",
    "stateName": "Glitch overlay",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-glitch--state-glitch--theme-ocean--bg-4",
    "previewId": "ui:icon-button:state:glitch",
    "stateId": "glitch",
    "stateName": "Glitch overlay",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-hover--state-hover--theme-aurora",
    "previewId": "ui:icon-button:state:hover",
    "stateId": "hover",
    "stateName": "Hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-hover--state-hover--theme-aurora--bg-1",
    "previewId": "ui:icon-button:state:hover",
    "stateId": "hover",
    "stateName": "Hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-hover--state-hover--theme-aurora--bg-2",
    "previewId": "ui:icon-button:state:hover",
    "stateId": "hover",
    "stateName": "Hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-hover--state-hover--theme-aurora--bg-3",
    "previewId": "ui:icon-button:state:hover",
    "stateId": "hover",
    "stateName": "Hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-hover--state-hover--theme-aurora--bg-4",
    "previewId": "ui:icon-button:state:hover",
    "stateId": "hover",
    "stateName": "Hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-hover--state-hover--theme-citrus",
    "previewId": "ui:icon-button:state:hover",
    "stateId": "hover",
    "stateName": "Hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-hover--state-hover--theme-citrus--bg-1",
    "previewId": "ui:icon-button:state:hover",
    "stateId": "hover",
    "stateName": "Hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-hover--state-hover--theme-citrus--bg-2",
    "previewId": "ui:icon-button:state:hover",
    "stateId": "hover",
    "stateName": "Hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-hover--state-hover--theme-citrus--bg-3",
    "previewId": "ui:icon-button:state:hover",
    "stateId": "hover",
    "stateName": "Hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-hover--state-hover--theme-citrus--bg-4",
    "previewId": "ui:icon-button:state:hover",
    "stateId": "hover",
    "stateName": "Hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-hover--state-hover--theme-hardstuck",
    "previewId": "ui:icon-button:state:hover",
    "stateId": "hover",
    "stateName": "Hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-hover--state-hover--theme-hardstuck--bg-1",
    "previewId": "ui:icon-button:state:hover",
    "stateId": "hover",
    "stateName": "Hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-hover--state-hover--theme-hardstuck--bg-2",
    "previewId": "ui:icon-button:state:hover",
    "stateId": "hover",
    "stateName": "Hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-hover--state-hover--theme-hardstuck--bg-3",
    "previewId": "ui:icon-button:state:hover",
    "stateId": "hover",
    "stateName": "Hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-hover--state-hover--theme-hardstuck--bg-4",
    "previewId": "ui:icon-button:state:hover",
    "stateId": "hover",
    "stateName": "Hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-hover--state-hover--theme-kitten",
    "previewId": "ui:icon-button:state:hover",
    "stateId": "hover",
    "stateName": "Hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-hover--state-hover--theme-kitten--bg-1",
    "previewId": "ui:icon-button:state:hover",
    "stateId": "hover",
    "stateName": "Hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-hover--state-hover--theme-kitten--bg-2",
    "previewId": "ui:icon-button:state:hover",
    "stateId": "hover",
    "stateName": "Hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-hover--state-hover--theme-kitten--bg-3",
    "previewId": "ui:icon-button:state:hover",
    "stateId": "hover",
    "stateName": "Hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-hover--state-hover--theme-kitten--bg-4",
    "previewId": "ui:icon-button:state:hover",
    "stateId": "hover",
    "stateName": "Hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-hover--state-hover--theme-lg",
    "previewId": "ui:icon-button:state:hover",
    "stateId": "hover",
    "stateName": "Hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-hover--state-hover--theme-lg--bg-1",
    "previewId": "ui:icon-button:state:hover",
    "stateId": "hover",
    "stateName": "Hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-hover--state-hover--theme-lg--bg-2",
    "previewId": "ui:icon-button:state:hover",
    "stateId": "hover",
    "stateName": "Hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-hover--state-hover--theme-lg--bg-3",
    "previewId": "ui:icon-button:state:hover",
    "stateId": "hover",
    "stateName": "Hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-hover--state-hover--theme-lg--bg-4",
    "previewId": "ui:icon-button:state:hover",
    "stateId": "hover",
    "stateName": "Hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-hover--state-hover--theme-noir",
    "previewId": "ui:icon-button:state:hover",
    "stateId": "hover",
    "stateName": "Hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-hover--state-hover--theme-noir--bg-1",
    "previewId": "ui:icon-button:state:hover",
    "stateId": "hover",
    "stateName": "Hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-hover--state-hover--theme-noir--bg-2",
    "previewId": "ui:icon-button:state:hover",
    "stateId": "hover",
    "stateName": "Hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-hover--state-hover--theme-noir--bg-3",
    "previewId": "ui:icon-button:state:hover",
    "stateId": "hover",
    "stateName": "Hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-hover--state-hover--theme-noir--bg-4",
    "previewId": "ui:icon-button:state:hover",
    "stateId": "hover",
    "stateName": "Hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-hover--state-hover--theme-ocean",
    "previewId": "ui:icon-button:state:hover",
    "stateId": "hover",
    "stateName": "Hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-hover--state-hover--theme-ocean--bg-1",
    "previewId": "ui:icon-button:state:hover",
    "stateId": "hover",
    "stateName": "Hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-hover--state-hover--theme-ocean--bg-2",
    "previewId": "ui:icon-button:state:hover",
    "stateId": "hover",
    "stateName": "Hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-hover--state-hover--theme-ocean--bg-3",
    "previewId": "ui:icon-button:state:hover",
    "stateId": "hover",
    "stateName": "Hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-hover--state-hover--theme-ocean--bg-4",
    "previewId": "ui:icon-button:state:hover",
    "stateId": "hover",
    "stateName": "Hover",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-loading--state-loading--theme-aurora",
    "previewId": "ui:icon-button:state:loading",
    "stateId": "loading",
    "stateName": "Loading",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-loading--state-loading--theme-aurora--bg-1",
    "previewId": "ui:icon-button:state:loading",
    "stateId": "loading",
    "stateName": "Loading",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-loading--state-loading--theme-aurora--bg-2",
    "previewId": "ui:icon-button:state:loading",
    "stateId": "loading",
    "stateName": "Loading",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-loading--state-loading--theme-aurora--bg-3",
    "previewId": "ui:icon-button:state:loading",
    "stateId": "loading",
    "stateName": "Loading",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-loading--state-loading--theme-aurora--bg-4",
    "previewId": "ui:icon-button:state:loading",
    "stateId": "loading",
    "stateName": "Loading",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-loading--state-loading--theme-citrus",
    "previewId": "ui:icon-button:state:loading",
    "stateId": "loading",
    "stateName": "Loading",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-loading--state-loading--theme-citrus--bg-1",
    "previewId": "ui:icon-button:state:loading",
    "stateId": "loading",
    "stateName": "Loading",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-loading--state-loading--theme-citrus--bg-2",
    "previewId": "ui:icon-button:state:loading",
    "stateId": "loading",
    "stateName": "Loading",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-loading--state-loading--theme-citrus--bg-3",
    "previewId": "ui:icon-button:state:loading",
    "stateId": "loading",
    "stateName": "Loading",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-loading--state-loading--theme-citrus--bg-4",
    "previewId": "ui:icon-button:state:loading",
    "stateId": "loading",
    "stateName": "Loading",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-loading--state-loading--theme-hardstuck",
    "previewId": "ui:icon-button:state:loading",
    "stateId": "loading",
    "stateName": "Loading",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-loading--state-loading--theme-hardstuck--bg-1",
    "previewId": "ui:icon-button:state:loading",
    "stateId": "loading",
    "stateName": "Loading",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-loading--state-loading--theme-hardstuck--bg-2",
    "previewId": "ui:icon-button:state:loading",
    "stateId": "loading",
    "stateName": "Loading",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-loading--state-loading--theme-hardstuck--bg-3",
    "previewId": "ui:icon-button:state:loading",
    "stateId": "loading",
    "stateName": "Loading",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-loading--state-loading--theme-hardstuck--bg-4",
    "previewId": "ui:icon-button:state:loading",
    "stateId": "loading",
    "stateName": "Loading",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-loading--state-loading--theme-kitten",
    "previewId": "ui:icon-button:state:loading",
    "stateId": "loading",
    "stateName": "Loading",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-loading--state-loading--theme-kitten--bg-1",
    "previewId": "ui:icon-button:state:loading",
    "stateId": "loading",
    "stateName": "Loading",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-loading--state-loading--theme-kitten--bg-2",
    "previewId": "ui:icon-button:state:loading",
    "stateId": "loading",
    "stateName": "Loading",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-loading--state-loading--theme-kitten--bg-3",
    "previewId": "ui:icon-button:state:loading",
    "stateId": "loading",
    "stateName": "Loading",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-loading--state-loading--theme-kitten--bg-4",
    "previewId": "ui:icon-button:state:loading",
    "stateId": "loading",
    "stateName": "Loading",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-loading--state-loading--theme-lg",
    "previewId": "ui:icon-button:state:loading",
    "stateId": "loading",
    "stateName": "Loading",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-loading--state-loading--theme-lg--bg-1",
    "previewId": "ui:icon-button:state:loading",
    "stateId": "loading",
    "stateName": "Loading",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-loading--state-loading--theme-lg--bg-2",
    "previewId": "ui:icon-button:state:loading",
    "stateId": "loading",
    "stateName": "Loading",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-loading--state-loading--theme-lg--bg-3",
    "previewId": "ui:icon-button:state:loading",
    "stateId": "loading",
    "stateName": "Loading",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-loading--state-loading--theme-lg--bg-4",
    "previewId": "ui:icon-button:state:loading",
    "stateId": "loading",
    "stateName": "Loading",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-loading--state-loading--theme-noir",
    "previewId": "ui:icon-button:state:loading",
    "stateId": "loading",
    "stateName": "Loading",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-loading--state-loading--theme-noir--bg-1",
    "previewId": "ui:icon-button:state:loading",
    "stateId": "loading",
    "stateName": "Loading",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-loading--state-loading--theme-noir--bg-2",
    "previewId": "ui:icon-button:state:loading",
    "stateId": "loading",
    "stateName": "Loading",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-loading--state-loading--theme-noir--bg-3",
    "previewId": "ui:icon-button:state:loading",
    "stateId": "loading",
    "stateName": "Loading",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-loading--state-loading--theme-noir--bg-4",
    "previewId": "ui:icon-button:state:loading",
    "stateId": "loading",
    "stateName": "Loading",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-loading--state-loading--theme-ocean",
    "previewId": "ui:icon-button:state:loading",
    "stateId": "loading",
    "stateName": "Loading",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-loading--state-loading--theme-ocean--bg-1",
    "previewId": "ui:icon-button:state:loading",
    "stateId": "loading",
    "stateName": "Loading",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-loading--state-loading--theme-ocean--bg-2",
    "previewId": "ui:icon-button:state:loading",
    "stateId": "loading",
    "stateName": "Loading",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-loading--state-loading--theme-ocean--bg-3",
    "previewId": "ui:icon-button:state:loading",
    "stateId": "loading",
    "stateName": "Loading",
    "slug": "section-buttons--entry-icon-button--preview-ui-icon-button-state-loading--state-loading--theme-ocean--bg-4",
    "previewId": "ui:icon-button:state:loading",
    "stateId": "loading",
    "stateName": "Loading",
      "ui:icon-button:state:default-variant",
      "ui:icon-button:state:default-hover",
      "ui:icon-button:state:default-active",
