export type TokenValue = string | string[];

export interface VariableDefinition {
  name: string;
  value: TokenValue;
}

export interface ThemeDefinition {
  id: string;
  label: string;
  description?: string[];
  variables: VariableDefinition[];
}

export const rootVariables: VariableDefinition[] = [
  { name: "lg-violet", value: "var(--ring)" },
  { name: "lg-cyan", value: "var(--accent-2)" },
  { name: "lg-pink", value: "var(--lav-deep)" },
  { name: "lg-black", value: "var(--background)" },
  { name: "card-foreground", value: "var(--foreground)" },
  { name: "header-stack", value: "calc(var(--spacing-8) + var(--spacing-4))" },
  {
    name: "shadow-neon",
    value: [
      "",
      "0 0 var(--space-1) hsl(var(--neon) / 0.55),",
      "0 0 calc(var(--space-3) - var(--space-1) / 2) hsl(var(--neon) / 0.35),",
      "0 0 calc(var(--space-4) + var(--space-1) / 2) hsl(var(--neon) / 0.2)",
    ],
  },
  {
    name: "btn-primary-hover-shadow",
    value: [
      "0 calc(var(--space-1) / 2) calc(var(--space-3) / 2)",
      "calc(-1 * var(--space-1) / 4) hsl(var(--accent) / 0.25)",
    ],
  },
  {
    name: "btn-primary-active-shadow",
    value: ["inset 0 0 0 calc(var(--space-1) / 4)", "hsl(var(--accent) / 0.6)"],
  },
  { name: "pillar-wave-start", value: "257 90% 70%" },
  { name: "pillar-wave-end", value: "198 90% 62%" },
  { name: "pillar-wave-shadow", value: "258 90% 38% / 0.35" },
  { name: "pillar-trading-start", value: "292 85% 72%" },
  { name: "pillar-trading-end", value: "318 85% 66%" },
  { name: "pillar-trading-shadow", value: "292 85% 38% / 0.35" },
  { name: "pillar-vision-start", value: "157 70% 55%" },
  { name: "pillar-vision-end", value: "192 75% 60%" },
  { name: "pillar-vision-shadow", value: "170 70% 30% / 0.35" },
  { name: "pillar-tempo-start", value: "260 85% 70%" },
  { name: "pillar-tempo-end", value: "284 85% 65%" },
  { name: "pillar-tempo-shadow", value: "270 80% 35% / 0.35" },
  { name: "pillar-positioning-start", value: "190 90% 66%" },
  { name: "pillar-positioning-end", value: "220 90% 66%" },
  { name: "pillar-positioning-shadow", value: "205 85% 35% / 0.35" },
  { name: "pillar-comms-start", value: "286 90% 68%" },
  { name: "pillar-comms-end", value: "312 88% 66%" },
  { name: "pillar-comms-shadow", value: "300 80% 36% / 0.35" },
];

export const themes: ThemeDefinition[] = [
  {
    id: "aurora",
    label: "Aurora",
    variables: [
      { name: "background", value: "283 100% 4%" },
      { name: "foreground", value: "260 20% 98%" },
      { name: "text", value: "var(--foreground)" },
      { name: "card", value: "281 100% 7%" },
      { name: "panel", value: "var(--card)" },
      { name: "border", value: "279 100% 15%" },
      { name: "line", value: "var(--border)" },
      { name: "input", value: "279 100% 15%" },
      { name: "ring", value: "150 100% 60%" },
      { name: "theme-ring", value: "hsl(var(--ring))" },
      { name: "primary", value: "150 100% 60%" },
      { name: "primary-foreground", value: "0 0% 100%" },
      { name: "primary-soft", value: "150 100% 20%" },
      { name: "accent", value: "272 80% 60%" },
      { name: "accent-2", value: "150 100% 60%" },
      { name: "accent-foreground", value: "0 0% 100%" },
      { name: "accent-soft", value: "272 80% 20%" },
      { name: "muted", value: "279 100% 15%" },
      { name: "muted-foreground", value: "279 20% 75%" },
      { name: "shadow-color", value: "150 100% 60%" },
      { name: "lav-deep", value: "272 80% 60%" },
      { name: "success", value: "150 70% 45%" },
      { name: "success-glow", value: "150 70% 35% / 0.6" },
      { name: "aurora-g", value: "var(--accent-2)" },
      {
        name: "aurora-g-light",
        value: "color-mix(in oklab, hsl(var(--accent-2)) 37.5%, white)",
      },
      { name: "aurora-p", value: "var(--accent)" },
      {
        name: "aurora-p-light",
        value: "color-mix(in oklab, hsl(var(--accent)) 37.5%, white)",
      },
      { name: "shadow-base", value: "279 30% 4%" },
      {
        name: "edge-iris",
        value: [
          "conic-gradient(",
          "from 180deg,",
          "hsl(var(--accent-2) / 0),",
          "hsl(var(--accent-2) / 0.7),",
          "hsl(var(--accent) / 0.7),",
          "hsl(var(--accent-2) / 0.7),",
          "hsl(var(--accent-2) / 0)",
          ")",
        ],
      },
      {
        name: "seg-active-grad",
        value: [
          "linear-gradient(",
          "90deg,",
          "hsl(var(--accent-2) / 0.35),",
          "hsl(var(--accent) / 0.35),",
          "hsl(var(--accent-2) / 0.35)",
          ")",
        ],
      },
      { name: "shadow", value: "0 10px 30px hsl(var(--shadow-base) / 0.3)" },
    ],
  },
  {
    id: "citrus",
    label: "Citrus",
    description: ["Dark citrus palette inspired by industrial orange hardware"],
    variables: [
      { name: "background", value: "216 15% 8%" },
      { name: "foreground", value: "30 35% 96%" },
      { name: "text", value: "var(--foreground)" },
      { name: "card", value: "214 20% 12%" },
      { name: "panel", value: "var(--card)" },
      { name: "border", value: "214 18% 28%" },
      { name: "line", value: "var(--border)" },
      { name: "input", value: "214 22% 16%" },
      { name: "ring", value: "24 95% 52%" },
      { name: "theme-ring", value: "hsl(var(--ring))" },
      { name: "primary", value: "24 95% 52%" },
      { name: "primary-foreground", value: "0 0% 100%" },
      { name: "primary-soft", value: "24 95% 22%" },
      { name: "accent", value: "24 96% 35%" },
      { name: "accent-2", value: "170 80% 25%" },
      { name: "accent-foreground", value: "0 0% 100%" },
      { name: "accent-soft", value: "24 96% 15%" },
      { name: "muted", value: "214 18% 24%" },
      { name: "muted-foreground", value: "214 20% 72%" },
      { name: "shadow-color", value: "24 95% 40%" },
      { name: "lav-deep", value: "24 95% 52%" },
      { name: "success", value: "150 70% 45%" },
      { name: "success-glow", value: "150 70% 35% / 0.6" },
      { name: "citrus-teal", value: "170 80% 45%" },
    ],
  },
  {
    id: "noir",
    label: "Noir",
    variables: [
      { name: "background", value: "350 70% 4%" },
      { name: "foreground", value: "0 0% 92%" },
      { name: "text", value: "var(--foreground)" },
      { name: "card", value: "350 65% 8%" },
      { name: "panel", value: "var(--card)" },
      { name: "border", value: "350 40% 22%" },
      { name: "line", value: "var(--border)" },
      { name: "input", value: "350 45% 12%" },
      { name: "ring", value: "0 90% 60%" },
      { name: "theme-ring", value: "hsl(var(--ring))" },
      { name: "primary", value: "0 90% 60%" },
      { name: "primary-foreground", value: "0 0% 100%" },
      { name: "primary-soft", value: "0 90% 24%" },
      { name: "accent", value: "178 91% 25%" },
      { name: "accent-2", value: "40 96% 25%" },
      { name: "accent-foreground", value: "0 0% 100%" },
      { name: "accent-soft", value: "178 91% 10%" },
      { name: "muted", value: "350 35% 18%" },
      { name: "muted-foreground", value: "350 25% 65%" },
      { name: "shadow-color", value: "0 90% 50%" },
      { name: "lav-deep", value: "0 90% 65%" },
      { name: "success", value: "140 60% 50%" },
      { name: "success-glow", value: "140 60% 40% / 0.6" },
      { name: "noir-red", value: "0 80% 60%" },
      { name: "noir-rose", value: "0 70% 55%" },
      { name: "noir-ink", value: "0 90% 6%" },
      { name: "noir-ruby", value: "0 60% 50%" },
    ],
  },
  {
    id: "ocean",
    label: "Oceanic",
    variables: [
      { name: "background", value: "220 50% 8%" },
      { name: "foreground", value: "210 20% 96%" },
      { name: "text", value: "var(--foreground)" },
      { name: "card", value: "220 35% 12%" },
      { name: "panel", value: "var(--card)" },
      { name: "border", value: "220 20% 24%" },
      { name: "line", value: "var(--border)" },
      { name: "input", value: "220 24% 14%" },
      { name: "ring", value: "195 85% 55%" },
      { name: "theme-ring", value: "hsl(var(--ring))" },
      { name: "primary", value: "195 85% 55%" },
      { name: "primary-foreground", value: "0 0% 100%" },
      { name: "primary-soft", value: "195 85% 16%" },
      { name: "accent", value: "199 100% 27%" },
      { name: "accent-2", value: "225 85% 30%" },
      { name: "accent-foreground", value: "0 0% 100%" },
      { name: "accent-soft", value: "199 100% 12%" },
      { name: "muted", value: "220 24% 16%" },
      { name: "muted-foreground", value: "220 14% 72%" },
      { name: "shadow-color", value: "200 90% 55%" },
      { name: "lav-deep", value: "250 80% 65%" },
      { name: "success", value: "160 70% 45%" },
      { name: "success-glow", value: "160 70% 35% / 0.6" },
      { name: "ocean-cyan", value: "190 90% 55%" },
      { name: "ocean-indigo", value: "225 85% 60%" },
    ],
  },
  {
    id: "kitten",
    label: "Kitten",
    variables: [
      { name: "background", value: "330 100% 2%" },
      { name: "foreground", value: "330 20% 96%" },
      { name: "text", value: "var(--foreground)" },
      { name: "card", value: "330 100% 6%" },
      { name: "panel", value: "var(--card)" },
      { name: "border", value: "330 100% 20%" },
      { name: "line", value: "var(--border)" },
      { name: "input", value: "330 100% 12%" },
      { name: "ring", value: "330 100% 52%" },
      { name: "theme-ring", value: "hsl(var(--ring))" },
      { name: "primary", value: "330 100% 52%" },
      { name: "primary-foreground", value: "0 0% 100%" },
      { name: "primary-soft", value: "330 100% 24%" },
      { name: "accent", value: "336 100% 27%" },
      { name: "accent-2", value: "196 100% 30%" },
      { name: "accent-foreground", value: "0 0% 100%" },
      { name: "accent-soft", value: "336 100% 12%" },
      { name: "muted", value: "330 100% 20%" },
      { name: "muted-foreground", value: "330 20% 70%" },
      { name: "shadow-color", value: "330 100% 50%" },
      { name: "lav-deep", value: "330 100% 60%" },
      { name: "success", value: "150 65% 45%" },
      { name: "success-glow", value: "150 65% 36% / 0.6" },
      { name: "kitten-rose", value: "343 100% 35%" },
      { name: "kitten-pink", value: "340 100% 45%" },
      { name: "kitten-blush", value: "347 100% 90%" },
    ],
  },
  {
    id: "hardstuck",
    label: "Hardstuck",
    variables: [
      { name: "background", value: "120 60% 2%" },
      { name: "foreground", value: "120 100% 70%" },
      { name: "text", value: "var(--foreground)" },
      { name: "card", value: "120 55% 5%" },
      { name: "panel", value: "var(--card)" },
      { name: "border", value: "120 40% 20%" },
      { name: "line", value: "var(--border)" },
      { name: "input", value: "120 45% 8%" },
      { name: "ring", value: "120 100% 60%" },
      { name: "theme-ring", value: "hsl(var(--ring))" },
      { name: "primary", value: "120 100% 60%" },
      { name: "primary-foreground", value: "0 0% 0%" },
      { name: "primary-soft", value: "120 100% 24%" },
      { name: "accent", value: "120 100% 60%" },
      { name: "accent-2", value: "120 100% 20%" },
      { name: "accent-foreground", value: "0 0% 0%" },
      { name: "text-on-accent", value: "hsl(var(--hardstuck-foreground))" },
      { name: "accent-soft", value: "120 100% 12%" },
      { name: "glow", value: "120 100% 68%" },
      { name: "ring-muted", value: "120 30% 20%" },
      { name: "danger", value: "0 84% 60%" },
      { name: "warning", value: "43 96% 56%" },
      { name: "muted", value: "120 35% 10%" },
      { name: "muted-foreground", value: "120 15% 70%" },
      { name: "surface", value: "120 32% 8%" },
      { name: "surface-2", value: "120 32% 12%" },
      { name: "surface-vhs", value: "120 27% 4%" },
      { name: "surface-streak", value: "120 16% 10%" },
      { name: "shadow-color", value: "120 100% 40%" },
      { name: "lav-deep", value: "120 100% 50%" },
      { name: "icon-fg", value: "120 100% 60%" },
      { name: "success", value: "120 100% 50%" },
      { name: "success-glow", value: "120 100% 40% / 0.6" },
      { name: "hardstuck-forest", value: "120 80% 40%" },
      { name: "hardstuck-deep", value: "120 90% 6%" },
    ],
  },
];
